// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: DeveloperRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	repository "github.com/qilin/crm-api/internal/domain/repository"
	reflect "reflect"
)

// MockDeveloperRepository is a mock of DeveloperRepository interface
type MockDeveloperRepository struct {
	ctrl     *gomock.Controller
	recorder *MockDeveloperRepositoryMockRecorder
}

// MockDeveloperRepositoryMockRecorder is the mock recorder for MockDeveloperRepository
type MockDeveloperRepositoryMockRecorder struct {
	mock *MockDeveloperRepository
}

// NewMockDeveloperRepository creates a new mock instance
func NewMockDeveloperRepository(ctrl *gomock.Controller) *MockDeveloperRepository {
	mock := &MockDeveloperRepository{ctrl: ctrl}
	mock.recorder = &MockDeveloperRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeveloperRepository) EXPECT() *MockDeveloperRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockDeveloperRepository) Create(arg0 context.Context, arg1 *entity.Developer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockDeveloperRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeveloperRepository)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockDeveloperRepository) Delete(arg0 context.Context, arg1 *entity.Developer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDeveloperRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeveloperRepository)(nil).Delete), arg0, arg1)
}

// FindByFilter mocks base method
func (m *MockDeveloperRepository) FindByFilter(arg0 context.Context, arg1 *repository.FindByFilterDeveloperData) ([]entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFilter", arg0, arg1)
	ret0, _ := ret[0].([]entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFilter indicates an expected call of FindByFilter
func (mr *MockDeveloperRepositoryMockRecorder) FindByFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFilter", reflect.TypeOf((*MockDeveloperRepository)(nil).FindByFilter), arg0, arg1)
}

// FindByID mocks base method
func (m *MockDeveloperRepository) FindByID(arg0 context.Context, arg1 uint) (*entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID
func (mr *MockDeveloperRepositoryMockRecorder) FindByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockDeveloperRepository)(nil).FindByID), arg0, arg1)
}

// FindByIDs mocks base method
func (m *MockDeveloperRepository) FindByIDs(arg0 context.Context, arg1 []uint) ([]entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByIDs", arg0, arg1)
	ret0, _ := ret[0].([]entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByIDs indicates an expected call of FindByIDs
func (mr *MockDeveloperRepositoryMockRecorder) FindByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByIDs", reflect.TypeOf((*MockDeveloperRepository)(nil).FindByIDs), arg0, arg1)
}

// Update mocks base method
func (m *MockDeveloperRepository) Update(arg0 context.Context, arg1 *entity.Developer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update
func (mr *MockDeveloperRepositoryMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeveloperRepository)(nil).Update), arg0, arg1)
}
