// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/service (interfaces: DeveloperService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	service "github.com/qilin/crm-api/internal/domain/service"
	reflect "reflect"
)

// MockDeveloperService is a mock of DeveloperService interface
type MockDeveloperService struct {
	ctrl     *gomock.Controller
	recorder *MockDeveloperServiceMockRecorder
}

// MockDeveloperServiceMockRecorder is the mock recorder for MockDeveloperService
type MockDeveloperServiceMockRecorder struct {
	mock *MockDeveloperService
}

// NewMockDeveloperService creates a new mock instance
func NewMockDeveloperService(ctrl *gomock.Controller) *MockDeveloperService {
	mock := &MockDeveloperService{ctrl: ctrl}
	mock.recorder = &MockDeveloperServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockDeveloperService) EXPECT() *MockDeveloperServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockDeveloperService) Create(arg0 context.Context, arg1 *service.CreateDeveloperData) (*entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockDeveloperServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDeveloperService)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockDeveloperService) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockDeveloperServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDeveloperService)(nil).Delete), arg0, arg1)
}

// GetByFilter mocks base method
func (m *MockDeveloperService) GetByFilter(arg0 context.Context, arg1 *service.GetByFilterDeveloperData) ([]entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByFilter", arg0, arg1)
	ret0, _ := ret[0].([]entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByFilter indicates an expected call of GetByFilter
func (mr *MockDeveloperServiceMockRecorder) GetByFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByFilter", reflect.TypeOf((*MockDeveloperService)(nil).GetByFilter), arg0, arg1)
}

// GetByGameRevisionID mocks base method
func (m *MockDeveloperService) GetByGameRevisionID(arg0 context.Context, arg1 uint) ([]entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGameRevisionID", arg0, arg1)
	ret0, _ := ret[0].([]entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGameRevisionID indicates an expected call of GetByGameRevisionID
func (mr *MockDeveloperServiceMockRecorder) GetByGameRevisionID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGameRevisionID", reflect.TypeOf((*MockDeveloperService)(nil).GetByGameRevisionID), arg0, arg1)
}

// GetByID mocks base method
func (m *MockDeveloperService) GetByID(arg0 context.Context, arg1 uint) (*entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockDeveloperServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockDeveloperService)(nil).GetByID), arg0, arg1)
}

// GetByIDs mocks base method
func (m *MockDeveloperService) GetByIDs(arg0 context.Context, arg1 []uint) ([]entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", arg0, arg1)
	ret0, _ := ret[0].([]entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs
func (mr *MockDeveloperServiceMockRecorder) GetByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockDeveloperService)(nil).GetByIDs), arg0, arg1)
}

// GetExistByID mocks base method
func (m *MockDeveloperService) GetExistByID(arg0 context.Context, arg1 uint) (*entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistByID indicates an expected call of GetExistByID
func (mr *MockDeveloperServiceMockRecorder) GetExistByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistByID", reflect.TypeOf((*MockDeveloperService)(nil).GetExistByID), arg0, arg1)
}

// Update mocks base method
func (m *MockDeveloperService) Update(arg0 context.Context, arg1 *service.UpdateDeveloperData) (*entity.Developer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*entity.Developer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockDeveloperServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockDeveloperService)(nil).Update), arg0, arg1)
}

// UpdateDevelopersForGameRevision mocks base method
func (m *MockDeveloperService) UpdateDevelopersForGameRevision(arg0 context.Context, arg1 *entity.GameRevision, arg2 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDevelopersForGameRevision", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDevelopersForGameRevision indicates an expected call of UpdateDevelopersForGameRevision
func (mr *MockDeveloperServiceMockRecorder) UpdateDevelopersForGameRevision(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDevelopersForGameRevision", reflect.TypeOf((*MockDeveloperService)(nil).UpdateDevelopersForGameRevision), arg0, arg1, arg2)
}
