// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/service (interfaces: GameService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	service "github.com/qilin/crm-api/internal/domain/service"
	reflect "reflect"
)

// MockGameService is a mock of GameService interface
type MockGameService struct {
	ctrl     *gomock.Controller
	recorder *MockGameServiceMockRecorder
}

// MockGameServiceMockRecorder is the mock recorder for MockGameService
type MockGameServiceMockRecorder struct {
	mock *MockGameService
}

// NewMockGameService creates a new mock instance
func NewMockGameService(ctrl *gomock.Controller) *MockGameService {
	mock := &MockGameService{ctrl: ctrl}
	mock.recorder = &MockGameServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameService) EXPECT() *MockGameServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGameService) Create(arg0 context.Context, arg1 *service.CreateGameData) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockGameServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameService)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockGameService) Delete(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameService)(nil).Delete), arg0, arg1)
}

// GetByID mocks base method
func (m *MockGameService) GetByID(arg0 context.Context, arg1 string) (*entity.Game, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Game)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockGameServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockGameService)(nil).GetByID), arg0, arg1)
}

// GetExByID mocks base method
func (m *MockGameService) GetExByID(arg0 context.Context, arg1 string) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExByID indicates an expected call of GetExByID
func (mr *MockGameServiceMockRecorder) GetExByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExByID", reflect.TypeOf((*MockGameService)(nil).GetExByID), arg0, arg1)
}

// GetExByIDAndRevisionID mocks base method
func (m *MockGameService) GetExByIDAndRevisionID(arg0 context.Context, arg1 string, arg2 uint) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExByIDAndRevisionID", arg0, arg1, arg2)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExByIDAndRevisionID indicates an expected call of GetExByIDAndRevisionID
func (mr *MockGameServiceMockRecorder) GetExByIDAndRevisionID(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExByIDAndRevisionID", reflect.TypeOf((*MockGameService)(nil).GetExByIDAndRevisionID), arg0, arg1, arg2)
}

// GetExBySlug mocks base method
func (m *MockGameService) GetExBySlug(arg0 context.Context, arg1 string) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExBySlug", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExBySlug indicates an expected call of GetExBySlug
func (mr *MockGameServiceMockRecorder) GetExBySlug(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExBySlug", reflect.TypeOf((*MockGameService)(nil).GetExBySlug), arg0, arg1)
}

// GetExLastPublishedByID mocks base method
func (m *MockGameService) GetExLastPublishedByID(arg0 context.Context, arg1 string) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExLastPublishedByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExLastPublishedByID indicates an expected call of GetExLastPublishedByID
func (mr *MockGameServiceMockRecorder) GetExLastPublishedByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExLastPublishedByID", reflect.TypeOf((*MockGameService)(nil).GetExLastPublishedByID), arg0, arg1)
}

// Publish mocks base method
func (m *MockGameService) Publish(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish
func (mr *MockGameServiceMockRecorder) Publish(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockGameService)(nil).Publish), arg0, arg1)
}

// Update mocks base method
func (m *MockGameService) Update(arg0 context.Context, arg1 *service.UpdateGameData) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockGameServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockGameService)(nil).Update), arg0, arg1)
}

// Upsert mocks base method
func (m *MockGameService) Upsert(arg0 context.Context, arg1 *service.UpsertGameData) (*entity.GameEx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", arg0, arg1)
	ret0, _ := ret[0].(*entity.GameEx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert
func (mr *MockGameServiceMockRecorder) Upsert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockGameService)(nil).Upsert), arg0, arg1)
}
