// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: GameFeatureRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	reflect "reflect"
)

// MockGameFeatureRepository is a mock of GameFeatureRepository interface
type MockGameFeatureRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameFeatureRepositoryMockRecorder
}

// MockGameFeatureRepositoryMockRecorder is the mock recorder for MockGameFeatureRepository
type MockGameFeatureRepositoryMockRecorder struct {
	mock *MockGameFeatureRepository
}

// NewMockGameFeatureRepository creates a new mock instance
func NewMockGameFeatureRepository(ctrl *gomock.Controller) *MockGameFeatureRepository {
	mock := &MockGameFeatureRepository{ctrl: ctrl}
	mock.recorder = &MockGameFeatureRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameFeatureRepository) EXPECT() *MockGameFeatureRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGameFeatureRepository) Create(arg0 context.Context, arg1 *entity.GameFeature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockGameFeatureRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameFeatureRepository)(nil).Create), arg0, arg1)
}

// CreateMultiple mocks base method
func (m *MockGameFeatureRepository) CreateMultiple(arg0 context.Context, arg1 []entity.GameFeature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultiple indicates an expected call of CreateMultiple
func (mr *MockGameFeatureRepositoryMockRecorder) CreateMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiple", reflect.TypeOf((*MockGameFeatureRepository)(nil).CreateMultiple), arg0, arg1)
}

// Delete mocks base method
func (m *MockGameFeatureRepository) Delete(arg0 context.Context, arg1 *entity.GameFeature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameFeatureRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameFeatureRepository)(nil).Delete), arg0, arg1)
}

// DeleteMultiple mocks base method
func (m *MockGameFeatureRepository) DeleteMultiple(arg0 context.Context, arg1 []entity.GameFeature) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultiple indicates an expected call of DeleteMultiple
func (mr *MockGameFeatureRepositoryMockRecorder) DeleteMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockGameFeatureRepository)(nil).DeleteMultiple), arg0, arg1)
}

// FindByFeatureID mocks base method
func (m *MockGameFeatureRepository) FindByFeatureID(arg0 context.Context, arg1 uint) ([]entity.GameFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByFeatureID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByFeatureID indicates an expected call of FindByFeatureID
func (mr *MockGameFeatureRepositoryMockRecorder) FindByFeatureID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByFeatureID", reflect.TypeOf((*MockGameFeatureRepository)(nil).FindByFeatureID), arg0, arg1)
}

// FindByGameID mocks base method
func (m *MockGameFeatureRepository) FindByGameID(arg0 context.Context, arg1 uint) ([]entity.GameFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameID indicates an expected call of FindByGameID
func (mr *MockGameFeatureRepositoryMockRecorder) FindByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameID", reflect.TypeOf((*MockGameFeatureRepository)(nil).FindByGameID), arg0, arg1)
}

// FindByGameIDAndFeatureIDs mocks base method
func (m *MockGameFeatureRepository) FindByGameIDAndFeatureIDs(arg0 context.Context, arg1 uint, arg2 []uint) ([]entity.GameFeature, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameIDAndFeatureIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.GameFeature)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameIDAndFeatureIDs indicates an expected call of FindByGameIDAndFeatureIDs
func (mr *MockGameFeatureRepositoryMockRecorder) FindByGameIDAndFeatureIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameIDAndFeatureIDs", reflect.TypeOf((*MockGameFeatureRepository)(nil).FindByGameIDAndFeatureIDs), arg0, arg1, arg2)
}
