// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: GameRevisionGenreRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	reflect "reflect"
)

// MockGameRevisionGenreRepository is a mock of GameRevisionGenreRepository interface
type MockGameRevisionGenreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameRevisionGenreRepositoryMockRecorder
}

// MockGameRevisionGenreRepositoryMockRecorder is the mock recorder for MockGameRevisionGenreRepository
type MockGameRevisionGenreRepositoryMockRecorder struct {
	mock *MockGameRevisionGenreRepository
}

// NewMockGameRevisionGenreRepository creates a new mock instance
func NewMockGameRevisionGenreRepository(ctrl *gomock.Controller) *MockGameRevisionGenreRepository {
	mock := &MockGameRevisionGenreRepository{ctrl: ctrl}
	mock.recorder = &MockGameRevisionGenreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameRevisionGenreRepository) EXPECT() *MockGameRevisionGenreRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGameRevisionGenreRepository) Create(arg0 context.Context, arg1 *entity.GameRevisionGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockGameRevisionGenreRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).Create), arg0, arg1)
}

// CreateMultiple mocks base method
func (m *MockGameRevisionGenreRepository) CreateMultiple(arg0 context.Context, arg1 []entity.GameRevisionGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultiple indicates an expected call of CreateMultiple
func (mr *MockGameRevisionGenreRepositoryMockRecorder) CreateMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiple", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).CreateMultiple), arg0, arg1)
}

// Delete mocks base method
func (m *MockGameRevisionGenreRepository) Delete(arg0 context.Context, arg1 *entity.GameRevisionGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameRevisionGenreRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).Delete), arg0, arg1)
}

// DeleteMultiple mocks base method
func (m *MockGameRevisionGenreRepository) DeleteMultiple(arg0 context.Context, arg1 []entity.GameRevisionGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultiple indicates an expected call of DeleteMultiple
func (mr *MockGameRevisionGenreRepositoryMockRecorder) DeleteMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).DeleteMultiple), arg0, arg1)
}

// FindByGameRevisionID mocks base method
func (m *MockGameRevisionGenreRepository) FindByGameRevisionID(arg0 context.Context, arg1 uint) ([]entity.GameRevisionGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameRevisionID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameRevisionGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameRevisionID indicates an expected call of FindByGameRevisionID
func (mr *MockGameRevisionGenreRepositoryMockRecorder) FindByGameRevisionID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameRevisionID", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).FindByGameRevisionID), arg0, arg1)
}

// FindByGameRevisionIDAndGenreIDs mocks base method
func (m *MockGameRevisionGenreRepository) FindByGameRevisionIDAndGenreIDs(arg0 context.Context, arg1 uint, arg2 []uint) ([]entity.GameRevisionGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameRevisionIDAndGenreIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.GameRevisionGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameRevisionIDAndGenreIDs indicates an expected call of FindByGameRevisionIDAndGenreIDs
func (mr *MockGameRevisionGenreRepositoryMockRecorder) FindByGameRevisionIDAndGenreIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameRevisionIDAndGenreIDs", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).FindByGameRevisionIDAndGenreIDs), arg0, arg1, arg2)
}

// FindByGenreID mocks base method
func (m *MockGameRevisionGenreRepository) FindByGenreID(arg0 context.Context, arg1 uint) ([]entity.GameRevisionGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGenreID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameRevisionGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGenreID indicates an expected call of FindByGenreID
func (mr *MockGameRevisionGenreRepositoryMockRecorder) FindByGenreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGenreID", reflect.TypeOf((*MockGameRevisionGenreRepository)(nil).FindByGenreID), arg0, arg1)
}
