// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: GamePublisherRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	reflect "reflect"
)

// MockGamePublisherRepository is a mock of GamePublisherRepository interface
type MockGamePublisherRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGamePublisherRepositoryMockRecorder
}

// MockGamePublisherRepositoryMockRecorder is the mock recorder for MockGamePublisherRepository
type MockGamePublisherRepositoryMockRecorder struct {
	mock *MockGamePublisherRepository
}

// NewMockGamePublisherRepository creates a new mock instance
func NewMockGamePublisherRepository(ctrl *gomock.Controller) *MockGamePublisherRepository {
	mock := &MockGamePublisherRepository{ctrl: ctrl}
	mock.recorder = &MockGamePublisherRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGamePublisherRepository) EXPECT() *MockGamePublisherRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGamePublisherRepository) Create(arg0 context.Context, arg1 *entity.GamePublisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockGamePublisherRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGamePublisherRepository)(nil).Create), arg0, arg1)
}

// CreateMultiple mocks base method
func (m *MockGamePublisherRepository) CreateMultiple(arg0 context.Context, arg1 []entity.GamePublisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultiple indicates an expected call of CreateMultiple
func (mr *MockGamePublisherRepositoryMockRecorder) CreateMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiple", reflect.TypeOf((*MockGamePublisherRepository)(nil).CreateMultiple), arg0, arg1)
}

// Delete mocks base method
func (m *MockGamePublisherRepository) Delete(arg0 context.Context, arg1 *entity.GamePublisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGamePublisherRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGamePublisherRepository)(nil).Delete), arg0, arg1)
}

// DeleteMultiple mocks base method
func (m *MockGamePublisherRepository) DeleteMultiple(arg0 context.Context, arg1 []entity.GamePublisher) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultiple indicates an expected call of DeleteMultiple
func (mr *MockGamePublisherRepositoryMockRecorder) DeleteMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockGamePublisherRepository)(nil).DeleteMultiple), arg0, arg1)
}

// FindByGameID mocks base method
func (m *MockGamePublisherRepository) FindByGameID(arg0 context.Context, arg1 uint) ([]entity.GamePublisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GamePublisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameID indicates an expected call of FindByGameID
func (mr *MockGamePublisherRepositoryMockRecorder) FindByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameID", reflect.TypeOf((*MockGamePublisherRepository)(nil).FindByGameID), arg0, arg1)
}

// FindByGameIDAndPublisherIDs mocks base method
func (m *MockGamePublisherRepository) FindByGameIDAndPublisherIDs(arg0 context.Context, arg1 uint, arg2 []uint) ([]entity.GamePublisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameIDAndPublisherIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.GamePublisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameIDAndPublisherIDs indicates an expected call of FindByGameIDAndPublisherIDs
func (mr *MockGamePublisherRepositoryMockRecorder) FindByGameIDAndPublisherIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameIDAndPublisherIDs", reflect.TypeOf((*MockGamePublisherRepository)(nil).FindByGameIDAndPublisherIDs), arg0, arg1, arg2)
}

// FindByPublisherID mocks base method
func (m *MockGamePublisherRepository) FindByPublisherID(arg0 context.Context, arg1 uint) ([]entity.GamePublisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByPublisherID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GamePublisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByPublisherID indicates an expected call of FindByPublisherID
func (mr *MockGamePublisherRepositoryMockRecorder) FindByPublisherID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByPublisherID", reflect.TypeOf((*MockGamePublisherRepository)(nil).FindByPublisherID), arg0, arg1)
}
