// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: IGameTagRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	reflect "reflect"
)

// MockIGameTagRepository is a mock of IGameTagRepository interface
type MockIGameTagRepository struct {
	ctrl     *gomock.Controller
	recorder *MockIGameTagRepositoryMockRecorder
}

// MockIGameTagRepositoryMockRecorder is the mock recorder for MockIGameTagRepository
type MockIGameTagRepositoryMockRecorder struct {
	mock *MockIGameTagRepository
}

// NewMockIGameTagRepository creates a new mock instance
func NewMockIGameTagRepository(ctrl *gomock.Controller) *MockIGameTagRepository {
	mock := &MockIGameTagRepository{ctrl: ctrl}
	mock.recorder = &MockIGameTagRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockIGameTagRepository) EXPECT() *MockIGameTagRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockIGameTagRepository) Create(arg0 context.Context, arg1 *entity.GameTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockIGameTagRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIGameTagRepository)(nil).Create), arg0, arg1)
}

// CreateMultiple mocks base method
func (m *MockIGameTagRepository) CreateMultiple(arg0 context.Context, arg1 []entity.GameTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultiple indicates an expected call of CreateMultiple
func (mr *MockIGameTagRepositoryMockRecorder) CreateMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiple", reflect.TypeOf((*MockIGameTagRepository)(nil).CreateMultiple), arg0, arg1)
}

// Delete mocks base method
func (m *MockIGameTagRepository) Delete(arg0 context.Context, arg1 *entity.GameTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockIGameTagRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIGameTagRepository)(nil).Delete), arg0, arg1)
}

// DeleteMultiple mocks base method
func (m *MockIGameTagRepository) DeleteMultiple(arg0 context.Context, arg1 []entity.GameTag) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultiple indicates an expected call of DeleteMultiple
func (mr *MockIGameTagRepositoryMockRecorder) DeleteMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockIGameTagRepository)(nil).DeleteMultiple), arg0, arg1)
}

// FindByGameID mocks base method
func (m *MockIGameTagRepository) FindByGameID(arg0 context.Context, arg1 uint) ([]entity.GameTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameID indicates an expected call of FindByGameID
func (mr *MockIGameTagRepositoryMockRecorder) FindByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameID", reflect.TypeOf((*MockIGameTagRepository)(nil).FindByGameID), arg0, arg1)
}

// FindByGameIDAndTagIDs mocks base method
func (m *MockIGameTagRepository) FindByGameIDAndTagIDs(arg0 context.Context, arg1 uint, arg2 []uint) ([]entity.GameTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameIDAndTagIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.GameTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameIDAndTagIDs indicates an expected call of FindByGameIDAndTagIDs
func (mr *MockIGameTagRepositoryMockRecorder) FindByGameIDAndTagIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameIDAndTagIDs", reflect.TypeOf((*MockIGameTagRepository)(nil).FindByGameIDAndTagIDs), arg0, arg1, arg2)
}

// FindByTagID mocks base method
func (m *MockIGameTagRepository) FindByTagID(arg0 context.Context, arg1 uint) ([]entity.GameTag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTagID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameTag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTagID indicates an expected call of FindByTagID
func (mr *MockIGameTagRepositoryMockRecorder) FindByTagID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTagID", reflect.TypeOf((*MockIGameTagRepository)(nil).FindByTagID), arg0, arg1)
}
