// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/repository (interfaces: GameGenreRepository)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	reflect "reflect"
)

// MockGameGenreRepository is a mock of GameGenreRepository interface
type MockGameGenreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockGameGenreRepositoryMockRecorder
}

// MockGameGenreRepositoryMockRecorder is the mock recorder for MockGameGenreRepository
type MockGameGenreRepositoryMockRecorder struct {
	mock *MockGameGenreRepository
}

// NewMockGameGenreRepository creates a new mock instance
func NewMockGameGenreRepository(ctrl *gomock.Controller) *MockGameGenreRepository {
	mock := &MockGameGenreRepository{ctrl: ctrl}
	mock.recorder = &MockGameGenreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockGameGenreRepository) EXPECT() *MockGameGenreRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockGameGenreRepository) Create(arg0 context.Context, arg1 *entity.GameGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create
func (mr *MockGameGenreRepositoryMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockGameGenreRepository)(nil).Create), arg0, arg1)
}

// CreateMultiple mocks base method
func (m *MockGameGenreRepository) CreateMultiple(arg0 context.Context, arg1 []entity.GameGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateMultiple indicates an expected call of CreateMultiple
func (mr *MockGameGenreRepositoryMockRecorder) CreateMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMultiple", reflect.TypeOf((*MockGameGenreRepository)(nil).CreateMultiple), arg0, arg1)
}

// Delete mocks base method
func (m *MockGameGenreRepository) Delete(arg0 context.Context, arg1 *entity.GameGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockGameGenreRepositoryMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockGameGenreRepository)(nil).Delete), arg0, arg1)
}

// DeleteMultiple mocks base method
func (m *MockGameGenreRepository) DeleteMultiple(arg0 context.Context, arg1 []entity.GameGenre) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMultiple", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMultiple indicates an expected call of DeleteMultiple
func (mr *MockGameGenreRepositoryMockRecorder) DeleteMultiple(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMultiple", reflect.TypeOf((*MockGameGenreRepository)(nil).DeleteMultiple), arg0, arg1)
}

// FindByGameID mocks base method
func (m *MockGameGenreRepository) FindByGameID(arg0 context.Context, arg1 uint) ([]entity.GameGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameID indicates an expected call of FindByGameID
func (mr *MockGameGenreRepositoryMockRecorder) FindByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameID", reflect.TypeOf((*MockGameGenreRepository)(nil).FindByGameID), arg0, arg1)
}

// FindByGameIDAndGenreIDs mocks base method
func (m *MockGameGenreRepository) FindByGameIDAndGenreIDs(arg0 context.Context, arg1 uint, arg2 []uint) ([]entity.GameGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGameIDAndGenreIDs", arg0, arg1, arg2)
	ret0, _ := ret[0].([]entity.GameGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGameIDAndGenreIDs indicates an expected call of FindByGameIDAndGenreIDs
func (mr *MockGameGenreRepositoryMockRecorder) FindByGameIDAndGenreIDs(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGameIDAndGenreIDs", reflect.TypeOf((*MockGameGenreRepository)(nil).FindByGameIDAndGenreIDs), arg0, arg1, arg2)
}

// FindByGenreID mocks base method
func (m *MockGameGenreRepository) FindByGenreID(arg0 context.Context, arg1 uint) ([]entity.GameGenre, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByGenreID", arg0, arg1)
	ret0, _ := ret[0].([]entity.GameGenre)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByGenreID indicates an expected call of FindByGenreID
func (mr *MockGameGenreRepositoryMockRecorder) FindByGenreID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByGenreID", reflect.TypeOf((*MockGameGenreRepository)(nil).FindByGenreID), arg0, arg1)
}
