// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/qilin/crm-api/internal/domain/service (interfaces: PublisherService)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
	entity "github.com/qilin/crm-api/internal/domain/entity"
	service "github.com/qilin/crm-api/internal/domain/service"
	reflect "reflect"
)

// MockPublisherService is a mock of PublisherService interface
type MockPublisherService struct {
	ctrl     *gomock.Controller
	recorder *MockPublisherServiceMockRecorder
}

// MockPublisherServiceMockRecorder is the mock recorder for MockPublisherService
type MockPublisherServiceMockRecorder struct {
	mock *MockPublisherService
}

// NewMockPublisherService creates a new mock instance
func NewMockPublisherService(ctrl *gomock.Controller) *MockPublisherService {
	mock := &MockPublisherService{ctrl: ctrl}
	mock.recorder = &MockPublisherServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockPublisherService) EXPECT() *MockPublisherServiceMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockPublisherService) Create(arg0 context.Context, arg1 *service.CreatePublisherData) (*entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(*entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockPublisherServiceMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockPublisherService)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockPublisherService) Delete(arg0 context.Context, arg1 uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockPublisherServiceMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPublisherService)(nil).Delete), arg0, arg1)
}

// GetByGameID mocks base method
func (m *MockPublisherService) GetByGameID(arg0 context.Context, arg1 uint) ([]entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByGameID", arg0, arg1)
	ret0, _ := ret[0].([]entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByGameID indicates an expected call of GetByGameID
func (mr *MockPublisherServiceMockRecorder) GetByGameID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByGameID", reflect.TypeOf((*MockPublisherService)(nil).GetByGameID), arg0, arg1)
}

// GetByID mocks base method
func (m *MockPublisherService) GetByID(arg0 context.Context, arg1 uint) (*entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID
func (mr *MockPublisherServiceMockRecorder) GetByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockPublisherService)(nil).GetByID), arg0, arg1)
}

// GetByIDs mocks base method
func (m *MockPublisherService) GetByIDs(arg0 context.Context, arg1 []uint) ([]entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByIDs", arg0, arg1)
	ret0, _ := ret[0].([]entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByIDs indicates an expected call of GetByIDs
func (mr *MockPublisherServiceMockRecorder) GetByIDs(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByIDs", reflect.TypeOf((*MockPublisherService)(nil).GetByIDs), arg0, arg1)
}

// GetExistByID mocks base method
func (m *MockPublisherService) GetExistByID(arg0 context.Context, arg1 uint) (*entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExistByID", arg0, arg1)
	ret0, _ := ret[0].(*entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExistByID indicates an expected call of GetExistByID
func (mr *MockPublisherServiceMockRecorder) GetExistByID(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExistByID", reflect.TypeOf((*MockPublisherService)(nil).GetExistByID), arg0, arg1)
}

// Update mocks base method
func (m *MockPublisherService) Update(arg0 context.Context, arg1 *service.UpdatePublisherData) (*entity.Publisher, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1)
	ret0, _ := ret[0].(*entity.Publisher)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockPublisherServiceMockRecorder) Update(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPublisherService)(nil).Update), arg0, arg1)
}

// UpdatePublishersForGame mocks base method
func (m *MockPublisherService) UpdatePublishersForGame(arg0 context.Context, arg1 *entity.Game, arg2 []uint) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePublishersForGame", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePublishersForGame indicates an expected call of UpdatePublishersForGame
func (mr *MockPublisherServiceMockRecorder) UpdatePublishersForGame(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePublishersForGame", reflect.TypeOf((*MockPublisherService)(nil).UpdatePublishersForGame), arg0, arg1, arg2)
}
