language: go
sudo: false
go:
- 1.13.x
services:
- docker
cache:
  directories:
  - "$GOPATH/pkg/mod"
stages:
- test
- name: deploy
  if: branch IN (master) AND type != pull_request
jobs:
  include:
  - stage: test
    script:
    - go test --tags=integration ./... -coverprofile=coverage.out -covermode=atomic
      -p=1
    after_success:
    - bash <(curl -s https://codecov.io/bash)
  - stage: deploy
    services: docker
    install: true
    script:
    - docker run -it -e JENKINS_AUTH_TOKEN=$JENKINS_AUTH_TOKEN -e JENKINS_BUILD_TOKEN=$JENKINS_BUILD_TOKEN
      -e JENKINS_BUILD_PROJECT=$TRAVIS_REPO_SLUG -e JENKINS_BUILD_BRANCH=$TRAVIS_BRANCH
      p1hub/p1jenkinstrigger
notifications:
  email: false
  slack:
    secure: KjbzuYaAcZYjCDZfVE0rTGAB6mhq74IJczWYLETRk+6UYlTi6RcLfPi1iuHj7KLGsRD8WwWRoNszl6XFvZq+XLfEnvza+sk/OuEHWDacgY+z8q65cVH2Occ9AwQCa3HePmKU/BxC+CyO0GK1lm0HNXryty/KHcQHZQAmwg11xNzerjqDH4ZPgPo4USlHXhF4RZXezPWPWG5WqqOi/yaXmVHTxlhXCJzSu345h0yv4549x7lCZq9zCbVFJ6hJQWyhzdt4/70zckAqmb3V9RMNZzxr5KVTq7u5R3+e36uiYUOCF9HP1Cni4C32iinj0z2JPgXmOEUJZyk7u58yHmTNhSSUpj9zLiU8Re6gEOi1joW2PrgP9DyGQM3yco8you6UCPHzdSRZ6dTFN+p+o0Zadkk18OeGXQhYq2kd+kOsB1QULFS+Jt+sf85jKGOj6zlR/fCOTFa2MDKRXee0g5JMnRpNBfj8XCUT4t2Syo8txvG8EofbalX503ImzTbAbHqryCggXmyglKeglINZdevYLXInAYEtpyLC05LaOPYrGs/JFKfzqviguUd2E4yx3MhCqXhmV20IypCyjCavJPQqmVKEojhkJRD7vW1emWdCBuHbzUaYkDOlYNumey0Z7Y9RYFyQUwBjliK9JwbD0lNUFpu3PhTHjL8fRouoNGKPdVg=
