// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/document.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AddDocumentRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	DocID                uint64   `protobuf:"varint,2,opt,name=docID,proto3" json:"docID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AddDocumentRequest) Reset()         { *m = AddDocumentRequest{} }
func (m *AddDocumentRequest) String() string { return proto.CompactTextString(m) }
func (*AddDocumentRequest) ProtoMessage()    {}
func (*AddDocumentRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{0}
}

func (m *AddDocumentRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddDocumentRequest.Unmarshal(m, b)
}
func (m *AddDocumentRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddDocumentRequest.Marshal(b, m, deterministic)
}
func (m *AddDocumentRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddDocumentRequest.Merge(m, src)
}
func (m *AddDocumentRequest) XXX_Size() int {
	return xxx_messageInfo_AddDocumentRequest.Size(m)
}
func (m *AddDocumentRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddDocumentRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddDocumentRequest proto.InternalMessageInfo

func (m *AddDocumentRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *AddDocumentRequest) GetDocID() uint64 {
	if m != nil {
		return m.DocID
	}
	return 0
}

type GetDocumentByIDRequest struct {
	DocumentID           uint64   `protobuf:"varint,1,opt,name=documentID,proto3" json:"documentID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentByIDRequest) Reset()         { *m = GetDocumentByIDRequest{} }
func (m *GetDocumentByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentByIDRequest) ProtoMessage()    {}
func (*GetDocumentByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{1}
}

func (m *GetDocumentByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentByIDRequest.Unmarshal(m, b)
}
func (m *GetDocumentByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentByIDRequest.Merge(m, src)
}
func (m *GetDocumentByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentByIDRequest.Size(m)
}
func (m *GetDocumentByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentByIDRequest proto.InternalMessageInfo

func (m *GetDocumentByIDRequest) GetDocumentID() uint64 {
	if m != nil {
		return m.DocumentID
	}
	return 0
}

type Document struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,json=iD,proto3" json:"ID,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=Title,json=title,proto3" json:"Title,omitempty"`
	Text                 string   `protobuf:"bytes,3,opt,name=Text,json=text,proto3" json:"Text,omitempty"`
	Reason               string   `protobuf:"bytes,4,opt,name=Reason,json=reason,proto3" json:"Reason,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=Type,json=type,proto3" json:"Type,omitempty"`
	Language             string   `protobuf:"bytes,6,opt,name=Language,json=language,proto3" json:"Language,omitempty"`
	Version              string   `protobuf:"bytes,7,opt,name=Version,json=version,proto3" json:"Version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Document) Reset()         { *m = Document{} }
func (m *Document) String() string { return proto.CompactTextString(m) }
func (*Document) ProtoMessage()    {}
func (*Document) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{2}
}

func (m *Document) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Document.Unmarshal(m, b)
}
func (m *Document) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Document.Marshal(b, m, deterministic)
}
func (m *Document) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Document.Merge(m, src)
}
func (m *Document) XXX_Size() int {
	return xxx_messageInfo_Document.Size(m)
}
func (m *Document) XXX_DiscardUnknown() {
	xxx_messageInfo_Document.DiscardUnknown(m)
}

var xxx_messageInfo_Document proto.InternalMessageInfo

func (m *Document) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Document) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Document) GetText() string {
	if m != nil {
		return m.Text
	}
	return ""
}

func (m *Document) GetReason() string {
	if m != nil {
		return m.Reason
	}
	return ""
}

func (m *Document) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Document) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Document) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type DocumentResponse struct {
	Document             *Document `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DocumentResponse) Reset()         { *m = DocumentResponse{} }
func (m *DocumentResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentResponse) ProtoMessage()    {}
func (*DocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{3}
}

func (m *DocumentResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentResponse.Unmarshal(m, b)
}
func (m *DocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentResponse.Marshal(b, m, deterministic)
}
func (m *DocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentResponse.Merge(m, src)
}
func (m *DocumentResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentResponse.Size(m)
}
func (m *DocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentResponse proto.InternalMessageInfo

func (m *DocumentResponse) GetDocument() *Document {
	if m != nil {
		return m.Document
	}
	return nil
}

type DocumentsResponse struct {
	Documents            []*Document `protobuf:"bytes,1,rep,name=documents,proto3" json:"documents,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *DocumentsResponse) Reset()         { *m = DocumentsResponse{} }
func (m *DocumentsResponse) String() string { return proto.CompactTextString(m) }
func (*DocumentsResponse) ProtoMessage()    {}
func (*DocumentsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{4}
}

func (m *DocumentsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DocumentsResponse.Unmarshal(m, b)
}
func (m *DocumentsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DocumentsResponse.Marshal(b, m, deterministic)
}
func (m *DocumentsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DocumentsResponse.Merge(m, src)
}
func (m *DocumentsResponse) XXX_Size() int {
	return xxx_messageInfo_DocumentsResponse.Size(m)
}
func (m *DocumentsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DocumentsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DocumentsResponse proto.InternalMessageInfo

func (m *DocumentsResponse) GetDocuments() []*Document {
	if m != nil {
		return m.Documents
	}
	return nil
}

type GetDocumentsByUserIDRequest struct {
	UserID               string   `protobuf:"bytes,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Limit                uint32   `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset               uint32   `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDocumentsByUserIDRequest) Reset()         { *m = GetDocumentsByUserIDRequest{} }
func (m *GetDocumentsByUserIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetDocumentsByUserIDRequest) ProtoMessage()    {}
func (*GetDocumentsByUserIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_6f5aa9055c184377, []int{5}
}

func (m *GetDocumentsByUserIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDocumentsByUserIDRequest.Unmarshal(m, b)
}
func (m *GetDocumentsByUserIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDocumentsByUserIDRequest.Marshal(b, m, deterministic)
}
func (m *GetDocumentsByUserIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDocumentsByUserIDRequest.Merge(m, src)
}
func (m *GetDocumentsByUserIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetDocumentsByUserIDRequest.Size(m)
}
func (m *GetDocumentsByUserIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDocumentsByUserIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDocumentsByUserIDRequest proto.InternalMessageInfo

func (m *GetDocumentsByUserIDRequest) GetUserID() string {
	if m != nil {
		return m.UserID
	}
	return ""
}

func (m *GetDocumentsByUserIDRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *GetDocumentsByUserIDRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func init() {
	proto.RegisterType((*AddDocumentRequest)(nil), "proto.AddDocumentRequest")
	proto.RegisterType((*GetDocumentByIDRequest)(nil), "proto.GetDocumentByIDRequest")
	proto.RegisterType((*Document)(nil), "proto.Document")
	proto.RegisterType((*DocumentResponse)(nil), "proto.DocumentResponse")
	proto.RegisterType((*DocumentsResponse)(nil), "proto.DocumentsResponse")
	proto.RegisterType((*GetDocumentsByUserIDRequest)(nil), "proto.GetDocumentsByUserIDRequest")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/document.proto", fileDescriptor_6f5aa9055c184377)
}

var fileDescriptor_6f5aa9055c184377 = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xc5, 0xa9, 0x1d, 0x3b, 0x13, 0xf5, 0x83, 0x15, 0x2a, 0x4b, 0x50, 0x51, 0xb4, 0xa7, 0x4a,
	0x88, 0x46, 0x2a, 0x17, 0x6e, 0x08, 0xd7, 0x52, 0x15, 0x09, 0x2e, 0x4b, 0xe1, 0xc0, 0x2d, 0xd8,
	0x53, 0xcb, 0x22, 0xf5, 0x1a, 0xef, 0xba, 0x8a, 0xff, 0x10, 0x3f, 0x8e, 0x5f, 0x81, 0x32, 0xde,
	0x75, 0x42, 0x12, 0x21, 0x4e, 0xab, 0x37, 0xfb, 0xfc, 0xe6, 0xcd, 0xdb, 0x31, 0x5c, 0x54, 0x3f,
	0xf2, 0x59, 0x5e, 0x57, 0xe9, 0xac, 0xaa, 0x95, 0x51, 0xb3, 0x4c, 0xa5, 0xcd, 0x03, 0x96, 0xe6,
	0x8a, 0x20, 0x0b, 0xe8, 0x10, 0x31, 0xb0, 0x0f, 0x59, 0x96, 0xd8, 0x3b, 0x89, 0x3f, 0x1b, 0xd4,
	0x86, 0x9d, 0xc3, 0xb0, 0xd1, 0x58, 0xcf, 0x13, 0xee, 0x4d, 0xbd, 0xcb, 0x91, 0xb4, 0x88, 0x3d,
	0x83, 0x20, 0x53, 0xe9, 0x3c, 0xe1, 0x83, 0xa9, 0x77, 0xe9, 0xcb, 0x0e, 0x88, 0x77, 0x70, 0x7e,
	0x8b, 0xc6, 0x69, 0xc4, 0xed, 0x3c, 0x71, 0x3a, 0xaf, 0x00, 0x5c, 0x5b, 0xab, 0xe5, 0xcb, 0xad,
	0x8a, 0xf8, 0xe5, 0x41, 0xe4, 0xbe, 0x63, 0x27, 0x30, 0xe8, 0x49, 0x83, 0x82, 0x9a, 0xdd, 0x15,
	0x66, 0x89, 0xd4, 0x6c, 0x24, 0x03, 0xb3, 0x06, 0x8c, 0x81, 0x7f, 0x87, 0x2b, 0xc3, 0x8f, 0xa8,
	0xe8, 0x1b, 0x5c, 0x91, 0x5d, 0x89, 0x0b, 0xad, 0x4a, 0xee, 0x77, 0x76, 0x6b, 0x42, 0xc4, 0x6d,
	0x2b, 0xe4, 0x81, 0xe5, 0xb6, 0x15, 0xb2, 0x09, 0x44, 0x1f, 0x17, 0x65, 0xde, 0x2c, 0x72, 0xe4,
	0x43, 0xaa, 0x47, 0x4b, 0x8b, 0x19, 0x87, 0xf0, 0x2b, 0xd6, 0xba, 0x50, 0x25, 0x0f, 0xe9, 0x2a,
	0x7c, 0xec, 0xa0, 0x78, 0x0f, 0x67, 0x9b, 0x8c, 0x74, 0xa5, 0x4a, 0x8d, 0xec, 0x35, 0x44, 0x6e,
	0x14, 0x72, 0x3d, 0xbe, 0x3e, 0xed, 0xb2, 0xbd, 0xea, 0xa9, 0x3d, 0x41, 0xc4, 0xf0, 0xd4, 0x55,
	0x75, 0xaf, 0xf0, 0x06, 0x46, 0x8e, 0xa0, 0xb9, 0x37, 0x3d, 0x3a, 0x24, 0xb1, 0x61, 0x88, 0x14,
	0x5e, 0x6e, 0xe5, 0xac, 0xe3, 0xf6, 0x0b, 0xbd, 0xca, 0x7f, 0x3c, 0xda, 0xb2, 0x78, 0x28, 0x0c,
	0xe5, 0x78, 0x2c, 0x3b, 0xb0, 0x66, 0xab, 0xfb, 0x7b, 0x8d, 0x5d, 0x92, 0xc7, 0xd2, 0xa2, 0xeb,
	0xdf, 0x1e, 0x9c, 0xba, 0x16, 0x9f, 0xb1, 0x7e, 0x2c, 0x52, 0x64, 0x37, 0x30, 0xde, 0x5a, 0x12,
	0xf6, 0xc2, 0x7a, 0xdc, 0x5f, 0x9c, 0xc9, 0xf3, 0x5d, 0xfb, 0x76, 0x54, 0xf1, 0x84, 0xdd, 0x40,
	0x78, 0x8b, 0xb4, 0x1d, 0xec, 0xc2, 0xb2, 0x0e, 0x6f, 0xcd, 0xbf, 0x44, 0x3e, 0xc1, 0x98, 0x44,
	0xba, 0xc9, 0x99, 0xd8, 0x17, 0xda, 0x8d, 0x65, 0xc2, 0x77, 0xd4, 0xf4, 0x46, 0x2e, 0x3e, 0xfb,
	0x76, 0xf2, 0xf7, 0x5f, 0xf2, 0x7d, 0x48, 0xc7, 0xdb, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc7,
	0x2e, 0x29, 0x20, 0x3e, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DocumentServiceClient is the client API for DocumentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DocumentServiceClient interface {
	//
	AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	// GetByID returns document by id
	GetByID(ctx context.Context, in *GetDocumentByIDRequest, opts ...grpc.CallOption) (*DocumentResponse, error)
	// GetByFilter returns accepted user documents by filter
	GetByUserID(ctx context.Context, in *GetDocumentsByUserIDRequest, opts ...grpc.CallOption) (*DocumentsResponse, error)
}

type documentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDocumentServiceClient(cc grpc.ClientConnInterface) DocumentServiceClient {
	return &documentServiceClient{cc}
}

func (c *documentServiceClient) AddDocument(ctx context.Context, in *AddDocumentRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentService/AddDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetByID(ctx context.Context, in *GetDocumentByIDRequest, opts ...grpc.CallOption) (*DocumentResponse, error) {
	out := new(DocumentResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *documentServiceClient) GetByUserID(ctx context.Context, in *GetDocumentsByUserIDRequest, opts ...grpc.CallOption) (*DocumentsResponse, error) {
	out := new(DocumentsResponse)
	err := c.cc.Invoke(ctx, "/proto.DocumentService/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DocumentServiceServer is the server API for DocumentService service.
type DocumentServiceServer interface {
	//
	AddDocument(context.Context, *AddDocumentRequest) (*DocumentResponse, error)
	// GetByID returns document by id
	GetByID(context.Context, *GetDocumentByIDRequest) (*DocumentResponse, error)
	// GetByFilter returns accepted user documents by filter
	GetByUserID(context.Context, *GetDocumentsByUserIDRequest) (*DocumentsResponse, error)
}

// UnimplementedDocumentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDocumentServiceServer struct {
}

func (*UnimplementedDocumentServiceServer) AddDocument(ctx context.Context, req *AddDocumentRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddDocument not implemented")
}
func (*UnimplementedDocumentServiceServer) GetByID(ctx context.Context, req *GetDocumentByIDRequest) (*DocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedDocumentServiceServer) GetByUserID(ctx context.Context, req *GetDocumentsByUserIDRequest) (*DocumentsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}

func RegisterDocumentServiceServer(s *grpc.Server, srv DocumentServiceServer) {
	s.RegisterService(&_DocumentService_serviceDesc, srv)
}

func _DocumentService_AddDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddDocumentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).AddDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentService/AddDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).AddDocument(ctx, req.(*AddDocumentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetByID(ctx, req.(*GetDocumentByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DocumentService_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDocumentsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DocumentServiceServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.DocumentService/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DocumentServiceServer).GetByUserID(ctx, req.(*GetDocumentsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DocumentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.DocumentService",
	HandlerType: (*DocumentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddDocument",
			Handler:    _DocumentService_AddDocument_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _DocumentService_GetByID_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _DocumentService_GetByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/document.proto",
}
