// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/game.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FindByTitleRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Offset               uint32   `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                uint32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FindByTitleRequest) Reset()         { *m = FindByTitleRequest{} }
func (m *FindByTitleRequest) String() string { return proto.CompactTextString(m) }
func (*FindByTitleRequest) ProtoMessage()    {}
func (*FindByTitleRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{0}
}

func (m *FindByTitleRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FindByTitleRequest.Unmarshal(m, b)
}
func (m *FindByTitleRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FindByTitleRequest.Marshal(b, m, deterministic)
}
func (m *FindByTitleRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FindByTitleRequest.Merge(m, src)
}
func (m *FindByTitleRequest) XXX_Size() int {
	return xxx_messageInfo_FindByTitleRequest.Size(m)
}
func (m *FindByTitleRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FindByTitleRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FindByTitleRequest proto.InternalMessageInfo

func (m *FindByTitleRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *FindByTitleRequest) GetOffset() uint32 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *FindByTitleRequest) GetLimit() uint32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type GetBySlugRequest struct {
	Slug                 string   `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBySlugRequest) Reset()         { *m = GetBySlugRequest{} }
func (m *GetBySlugRequest) String() string { return proto.CompactTextString(m) }
func (*GetBySlugRequest) ProtoMessage()    {}
func (*GetBySlugRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{1}
}

func (m *GetBySlugRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBySlugRequest.Unmarshal(m, b)
}
func (m *GetBySlugRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBySlugRequest.Marshal(b, m, deterministic)
}
func (m *GetBySlugRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBySlugRequest.Merge(m, src)
}
func (m *GetBySlugRequest) XXX_Size() int {
	return xxx_messageInfo_GetBySlugRequest.Size(m)
}
func (m *GetBySlugRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBySlugRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBySlugRequest proto.InternalMessageInfo

func (m *GetBySlugRequest) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

type GetByIDRequest struct {
	GameID               string   `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetByIDRequest) Reset()         { *m = GetByIDRequest{} }
func (m *GetByIDRequest) String() string { return proto.CompactTextString(m) }
func (*GetByIDRequest) ProtoMessage()    {}
func (*GetByIDRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{2}
}

func (m *GetByIDRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetByIDRequest.Unmarshal(m, b)
}
func (m *GetByIDRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetByIDRequest.Marshal(b, m, deterministic)
}
func (m *GetByIDRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetByIDRequest.Merge(m, src)
}
func (m *GetByIDRequest) XXX_Size() int {
	return xxx_messageInfo_GetByIDRequest.Size(m)
}
func (m *GetByIDRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetByIDRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetByIDRequest proto.InternalMessageInfo

func (m *GetByIDRequest) GetGameID() string {
	if m != nil {
		return m.GameID
	}
	return ""
}

type Request struct {
	GameID               string   `protobuf:"bytes,1,opt,name=gameID,proto3" json:"gameID,omitempty"`
	RevisionID           uint64   `protobuf:"varint,2,opt,name=revisionID,proto3" json:"revisionID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{3}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetGameID() string {
	if m != nil {
		return m.GameID
	}
	return ""
}

func (m *Request) GetRevisionID() uint64 {
	if m != nil {
		return m.RevisionID
	}
	return 0
}

type SearchByTitleResponse struct {
	Games                []*Game  `protobuf:"bytes,1,rep,name=games,proto3" json:"games,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SearchByTitleResponse) Reset()         { *m = SearchByTitleResponse{} }
func (m *SearchByTitleResponse) String() string { return proto.CompactTextString(m) }
func (*SearchByTitleResponse) ProtoMessage()    {}
func (*SearchByTitleResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{4}
}

func (m *SearchByTitleResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SearchByTitleResponse.Unmarshal(m, b)
}
func (m *SearchByTitleResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SearchByTitleResponse.Marshal(b, m, deterministic)
}
func (m *SearchByTitleResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SearchByTitleResponse.Merge(m, src)
}
func (m *SearchByTitleResponse) XXX_Size() int {
	return xxx_messageInfo_SearchByTitleResponse.Size(m)
}
func (m *SearchByTitleResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SearchByTitleResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SearchByTitleResponse proto.InternalMessageInfo

func (m *SearchByTitleResponse) GetGames() []*Game {
	if m != nil {
		return m.Games
	}
	return nil
}

type GameResponse struct {
	Game                 *Game    `protobuf:"bytes,1,opt,name=game,proto3" json:"game,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameResponse) Reset()         { *m = GameResponse{} }
func (m *GameResponse) String() string { return proto.CompactTextString(m) }
func (*GameResponse) ProtoMessage()    {}
func (*GameResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{5}
}

func (m *GameResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameResponse.Unmarshal(m, b)
}
func (m *GameResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameResponse.Marshal(b, m, deterministic)
}
func (m *GameResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameResponse.Merge(m, src)
}
func (m *GameResponse) XXX_Size() int {
	return xxx_messageInfo_GameResponse.Size(m)
}
func (m *GameResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GameResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GameResponse proto.InternalMessageInfo

func (m *GameResponse) GetGame() *Game {
	if m != nil {
		return m.Game
	}
	return nil
}

type Game struct {
	ID                   string                `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Title                string                `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Type                 string                `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	RevisionID           uint64                `protobuf:"varint,4,opt,name=revisionID,proto3" json:"revisionID,omitempty"`
	Summary              string                `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Description          string                `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Slug                 string                `protobuf:"bytes,7,opt,name=slug,proto3" json:"slug,omitempty"`
	License              string                `protobuf:"bytes,8,opt,name=license,proto3" json:"license,omitempty"`
	Platforms            []string              `protobuf:"bytes,9,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Tags                 []*Tag                `protobuf:"bytes,10,rep,name=tags,proto3" json:"tags,omitempty"`
	Features             []*Feature            `protobuf:"bytes,11,rep,name=features,proto3" json:"features,omitempty"`
	Developers           []*Developer          `protobuf:"bytes,12,rep,name=developers,proto3" json:"developers,omitempty"`
	Genres               []*Genre              `protobuf:"bytes,13,rep,name=genres,proto3" json:"genres,omitempty"`
	Publishers           []*Publisher          `protobuf:"bytes,14,rep,name=publishers,proto3" json:"publishers,omitempty"`
	SystemRequirements   []*SystemRequirements `protobuf:"bytes,15,rep,name=systemRequirements,proto3" json:"systemRequirements,omitempty"`
	Localizations        []*Localization       `protobuf:"bytes,16,rep,name=localizations,proto3" json:"localizations,omitempty"`
	Trailer              string                `protobuf:"bytes,17,opt,name=trailer,proto3" json:"trailer,omitempty"`
	SocialLinks          []*SocialLink         `protobuf:"bytes,18,rep,name=socialLinks,proto3" json:"socialLinks,omitempty"`
	Rating               []*Rating             `protobuf:"bytes,19,rep,name=rating,proto3" json:"rating,omitempty"`
	Media                []*Media              `protobuf:"bytes,20,rep,name=media,proto3" json:"media,omitempty"`
	Reviews              []*Review             `protobuf:"bytes,21,rep,name=reviews,proto3" json:"reviews,omitempty"`
	PlayTime             uint32                `protobuf:"varint,22,opt,name=playTime,proto3" json:"playTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Game) Reset()         { *m = Game{} }
func (m *Game) String() string { return proto.CompactTextString(m) }
func (*Game) ProtoMessage()    {}
func (*Game) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{6}
}

func (m *Game) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Game.Unmarshal(m, b)
}
func (m *Game) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Game.Marshal(b, m, deterministic)
}
func (m *Game) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Game.Merge(m, src)
}
func (m *Game) XXX_Size() int {
	return xxx_messageInfo_Game.Size(m)
}
func (m *Game) XXX_DiscardUnknown() {
	xxx_messageInfo_Game.DiscardUnknown(m)
}

var xxx_messageInfo_Game proto.InternalMessageInfo

func (m *Game) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Game) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Game) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Game) GetRevisionID() uint64 {
	if m != nil {
		return m.RevisionID
	}
	return 0
}

func (m *Game) GetSummary() string {
	if m != nil {
		return m.Summary
	}
	return ""
}

func (m *Game) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Game) GetSlug() string {
	if m != nil {
		return m.Slug
	}
	return ""
}

func (m *Game) GetLicense() string {
	if m != nil {
		return m.License
	}
	return ""
}

func (m *Game) GetPlatforms() []string {
	if m != nil {
		return m.Platforms
	}
	return nil
}

func (m *Game) GetTags() []*Tag {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Game) GetFeatures() []*Feature {
	if m != nil {
		return m.Features
	}
	return nil
}

func (m *Game) GetDevelopers() []*Developer {
	if m != nil {
		return m.Developers
	}
	return nil
}

func (m *Game) GetGenres() []*Genre {
	if m != nil {
		return m.Genres
	}
	return nil
}

func (m *Game) GetPublishers() []*Publisher {
	if m != nil {
		return m.Publishers
	}
	return nil
}

func (m *Game) GetSystemRequirements() []*SystemRequirements {
	if m != nil {
		return m.SystemRequirements
	}
	return nil
}

func (m *Game) GetLocalizations() []*Localization {
	if m != nil {
		return m.Localizations
	}
	return nil
}

func (m *Game) GetTrailer() string {
	if m != nil {
		return m.Trailer
	}
	return ""
}

func (m *Game) GetSocialLinks() []*SocialLink {
	if m != nil {
		return m.SocialLinks
	}
	return nil
}

func (m *Game) GetRating() []*Rating {
	if m != nil {
		return m.Rating
	}
	return nil
}

func (m *Game) GetMedia() []*Media {
	if m != nil {
		return m.Media
	}
	return nil
}

func (m *Game) GetReviews() []*Review {
	if m != nil {
		return m.Reviews
	}
	return nil
}

func (m *Game) GetPlayTime() uint32 {
	if m != nil {
		return m.PlayTime
	}
	return 0
}

type Media struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Media) Reset()         { *m = Media{} }
func (m *Media) String() string { return proto.CompactTextString(m) }
func (*Media) ProtoMessage()    {}
func (*Media) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{7}
}

func (m *Media) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Media.Unmarshal(m, b)
}
func (m *Media) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Media.Marshal(b, m, deterministic)
}
func (m *Media) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Media.Merge(m, src)
}
func (m *Media) XXX_Size() int {
	return xxx_messageInfo_Media.Size(m)
}
func (m *Media) XXX_DiscardUnknown() {
	xxx_messageInfo_Media.DiscardUnknown(m)
}

var xxx_messageInfo_Media proto.InternalMessageInfo

func (m *Media) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Media) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Tag struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Tag) Reset()         { *m = Tag{} }
func (m *Tag) String() string { return proto.CompactTextString(m) }
func (*Tag) ProtoMessage()    {}
func (*Tag) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{8}
}

func (m *Tag) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Tag.Unmarshal(m, b)
}
func (m *Tag) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Tag.Marshal(b, m, deterministic)
}
func (m *Tag) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Tag.Merge(m, src)
}
func (m *Tag) XXX_Size() int {
	return xxx_messageInfo_Tag.Size(m)
}
func (m *Tag) XXX_DiscardUnknown() {
	xxx_messageInfo_Tag.DiscardUnknown(m)
}

var xxx_messageInfo_Tag proto.InternalMessageInfo

func (m *Tag) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Tag) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Developer struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Developer) Reset()         { *m = Developer{} }
func (m *Developer) String() string { return proto.CompactTextString(m) }
func (*Developer) ProtoMessage()    {}
func (*Developer) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{9}
}

func (m *Developer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Developer.Unmarshal(m, b)
}
func (m *Developer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Developer.Marshal(b, m, deterministic)
}
func (m *Developer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Developer.Merge(m, src)
}
func (m *Developer) XXX_Size() int {
	return xxx_messageInfo_Developer.Size(m)
}
func (m *Developer) XXX_DiscardUnknown() {
	xxx_messageInfo_Developer.DiscardUnknown(m)
}

var xxx_messageInfo_Developer proto.InternalMessageInfo

func (m *Developer) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Developer) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Feature struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Icon                 string   `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Feature) Reset()         { *m = Feature{} }
func (m *Feature) String() string { return proto.CompactTextString(m) }
func (*Feature) ProtoMessage()    {}
func (*Feature) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{10}
}

func (m *Feature) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Feature.Unmarshal(m, b)
}
func (m *Feature) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Feature.Marshal(b, m, deterministic)
}
func (m *Feature) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Feature.Merge(m, src)
}
func (m *Feature) XXX_Size() int {
	return xxx_messageInfo_Feature.Size(m)
}
func (m *Feature) XXX_DiscardUnknown() {
	xxx_messageInfo_Feature.DiscardUnknown(m)
}

var xxx_messageInfo_Feature proto.InternalMessageInfo

func (m *Feature) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Feature) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Feature) GetIcon() string {
	if m != nil {
		return m.Icon
	}
	return ""
}

type Genre struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Genre) Reset()         { *m = Genre{} }
func (m *Genre) String() string { return proto.CompactTextString(m) }
func (*Genre) ProtoMessage()    {}
func (*Genre) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{11}
}

func (m *Genre) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Genre.Unmarshal(m, b)
}
func (m *Genre) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Genre.Marshal(b, m, deterministic)
}
func (m *Genre) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Genre.Merge(m, src)
}
func (m *Genre) XXX_Size() int {
	return xxx_messageInfo_Genre.Size(m)
}
func (m *Genre) XXX_DiscardUnknown() {
	xxx_messageInfo_Genre.DiscardUnknown(m)
}

var xxx_messageInfo_Genre proto.InternalMessageInfo

func (m *Genre) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Genre) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Publisher struct {
	ID                   uint64   `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Publisher) Reset()         { *m = Publisher{} }
func (m *Publisher) String() string { return proto.CompactTextString(m) }
func (*Publisher) ProtoMessage()    {}
func (*Publisher) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{12}
}

func (m *Publisher) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Publisher.Unmarshal(m, b)
}
func (m *Publisher) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Publisher.Marshal(b, m, deterministic)
}
func (m *Publisher) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Publisher.Merge(m, src)
}
func (m *Publisher) XXX_Size() int {
	return xxx_messageInfo_Publisher.Size(m)
}
func (m *Publisher) XXX_DiscardUnknown() {
	xxx_messageInfo_Publisher.DiscardUnknown(m)
}

var xxx_messageInfo_Publisher proto.InternalMessageInfo

func (m *Publisher) GetID() uint64 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Publisher) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type SystemRequirements struct {
	Platform             string           `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Minimal              *RequirementsSet `protobuf:"bytes,2,opt,name=minimal,proto3" json:"minimal,omitempty"`
	Recommended          *RequirementsSet `protobuf:"bytes,3,opt,name=recommended,proto3" json:"recommended,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *SystemRequirements) Reset()         { *m = SystemRequirements{} }
func (m *SystemRequirements) String() string { return proto.CompactTextString(m) }
func (*SystemRequirements) ProtoMessage()    {}
func (*SystemRequirements) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{13}
}

func (m *SystemRequirements) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SystemRequirements.Unmarshal(m, b)
}
func (m *SystemRequirements) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SystemRequirements.Marshal(b, m, deterministic)
}
func (m *SystemRequirements) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SystemRequirements.Merge(m, src)
}
func (m *SystemRequirements) XXX_Size() int {
	return xxx_messageInfo_SystemRequirements.Size(m)
}
func (m *SystemRequirements) XXX_DiscardUnknown() {
	xxx_messageInfo_SystemRequirements.DiscardUnknown(m)
}

var xxx_messageInfo_SystemRequirements proto.InternalMessageInfo

func (m *SystemRequirements) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *SystemRequirements) GetMinimal() *RequirementsSet {
	if m != nil {
		return m.Minimal
	}
	return nil
}

func (m *SystemRequirements) GetRecommended() *RequirementsSet {
	if m != nil {
		return m.Recommended
	}
	return nil
}

type RequirementsSet struct {
	CPU                  string   `protobuf:"bytes,1,opt,name=CPU,proto3" json:"CPU,omitempty"`
	GPU                  string   `protobuf:"bytes,2,opt,name=GPU,proto3" json:"GPU,omitempty"`
	DiskSpace            uint32   `protobuf:"varint,3,opt,name=DiskSpace,proto3" json:"DiskSpace,omitempty"`
	RAM                  uint32   `protobuf:"varint,4,opt,name=RAM,proto3" json:"RAM,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequirementsSet) Reset()         { *m = RequirementsSet{} }
func (m *RequirementsSet) String() string { return proto.CompactTextString(m) }
func (*RequirementsSet) ProtoMessage()    {}
func (*RequirementsSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{14}
}

func (m *RequirementsSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequirementsSet.Unmarshal(m, b)
}
func (m *RequirementsSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequirementsSet.Marshal(b, m, deterministic)
}
func (m *RequirementsSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequirementsSet.Merge(m, src)
}
func (m *RequirementsSet) XXX_Size() int {
	return xxx_messageInfo_RequirementsSet.Size(m)
}
func (m *RequirementsSet) XXX_DiscardUnknown() {
	xxx_messageInfo_RequirementsSet.DiscardUnknown(m)
}

var xxx_messageInfo_RequirementsSet proto.InternalMessageInfo

func (m *RequirementsSet) GetCPU() string {
	if m != nil {
		return m.CPU
	}
	return ""
}

func (m *RequirementsSet) GetGPU() string {
	if m != nil {
		return m.GPU
	}
	return ""
}

func (m *RequirementsSet) GetDiskSpace() uint32 {
	if m != nil {
		return m.DiskSpace
	}
	return 0
}

func (m *RequirementsSet) GetRAM() uint32 {
	if m != nil {
		return m.RAM
	}
	return 0
}

type Localization struct {
	Language             string   `protobuf:"bytes,1,opt,name=Language,proto3" json:"Language,omitempty"`
	Interface            bool     `protobuf:"varint,2,opt,name=Interface,proto3" json:"Interface,omitempty"`
	Audio                bool     `protobuf:"varint,3,opt,name=Audio,proto3" json:"Audio,omitempty"`
	Subtitles            bool     `protobuf:"varint,4,opt,name=Subtitles,proto3" json:"Subtitles,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Localization) Reset()         { *m = Localization{} }
func (m *Localization) String() string { return proto.CompactTextString(m) }
func (*Localization) ProtoMessage()    {}
func (*Localization) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{15}
}

func (m *Localization) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Localization.Unmarshal(m, b)
}
func (m *Localization) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Localization.Marshal(b, m, deterministic)
}
func (m *Localization) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Localization.Merge(m, src)
}
func (m *Localization) XXX_Size() int {
	return xxx_messageInfo_Localization.Size(m)
}
func (m *Localization) XXX_DiscardUnknown() {
	xxx_messageInfo_Localization.DiscardUnknown(m)
}

var xxx_messageInfo_Localization proto.InternalMessageInfo

func (m *Localization) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

func (m *Localization) GetInterface() bool {
	if m != nil {
		return m.Interface
	}
	return false
}

func (m *Localization) GetAudio() bool {
	if m != nil {
		return m.Audio
	}
	return false
}

func (m *Localization) GetSubtitles() bool {
	if m != nil {
		return m.Subtitles
	}
	return false
}

type SocialLink struct {
	Url                  string   `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SocialLink) Reset()         { *m = SocialLink{} }
func (m *SocialLink) String() string { return proto.CompactTextString(m) }
func (*SocialLink) ProtoMessage()    {}
func (*SocialLink) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{16}
}

func (m *SocialLink) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SocialLink.Unmarshal(m, b)
}
func (m *SocialLink) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SocialLink.Marshal(b, m, deterministic)
}
func (m *SocialLink) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SocialLink.Merge(m, src)
}
func (m *SocialLink) XXX_Size() int {
	return xxx_messageInfo_SocialLink.Size(m)
}
func (m *SocialLink) XXX_DiscardUnknown() {
	xxx_messageInfo_SocialLink.DiscardUnknown(m)
}

var xxx_messageInfo_SocialLink proto.InternalMessageInfo

func (m *SocialLink) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type Rating struct {
	Agency               string   `protobuf:"bytes,1,opt,name=Agency,proto3" json:"Agency,omitempty"`
	Rating               string   `protobuf:"bytes,2,opt,name=Rating,proto3" json:"Rating,omitempty"`
	DisplayOnlineNotice  bool     `protobuf:"varint,3,opt,name=DisplayOnlineNotice,proto3" json:"DisplayOnlineNotice,omitempty"`
	ShowAgeRestrict      bool     `protobuf:"varint,4,opt,name=ShowAgeRestrict,proto3" json:"ShowAgeRestrict,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rating) Reset()         { *m = Rating{} }
func (m *Rating) String() string { return proto.CompactTextString(m) }
func (*Rating) ProtoMessage()    {}
func (*Rating) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{17}
}

func (m *Rating) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rating.Unmarshal(m, b)
}
func (m *Rating) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rating.Marshal(b, m, deterministic)
}
func (m *Rating) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rating.Merge(m, src)
}
func (m *Rating) XXX_Size() int {
	return xxx_messageInfo_Rating.Size(m)
}
func (m *Rating) XXX_DiscardUnknown() {
	xxx_messageInfo_Rating.DiscardUnknown(m)
}

var xxx_messageInfo_Rating proto.InternalMessageInfo

func (m *Rating) GetAgency() string {
	if m != nil {
		return m.Agency
	}
	return ""
}

func (m *Rating) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *Rating) GetDisplayOnlineNotice() bool {
	if m != nil {
		return m.DisplayOnlineNotice
	}
	return false
}

func (m *Rating) GetShowAgeRestrict() bool {
	if m != nil {
		return m.ShowAgeRestrict
	}
	return false
}

type Review struct {
	PressName            string   `protobuf:"bytes,1,opt,name=PressName,proto3" json:"PressName,omitempty"`
	Link                 string   `protobuf:"bytes,2,opt,name=Link,proto3" json:"Link,omitempty"`
	Score                string   `protobuf:"bytes,3,opt,name=Score,proto3" json:"Score,omitempty"`
	Quote                string   `protobuf:"bytes,4,opt,name=Quote,proto3" json:"Quote,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Review) Reset()         { *m = Review{} }
func (m *Review) String() string { return proto.CompactTextString(m) }
func (*Review) ProtoMessage()    {}
func (*Review) Descriptor() ([]byte, []int) {
	return fileDescriptor_07bb4d05826a653a, []int{18}
}

func (m *Review) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Review.Unmarshal(m, b)
}
func (m *Review) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Review.Marshal(b, m, deterministic)
}
func (m *Review) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Review.Merge(m, src)
}
func (m *Review) XXX_Size() int {
	return xxx_messageInfo_Review.Size(m)
}
func (m *Review) XXX_DiscardUnknown() {
	xxx_messageInfo_Review.DiscardUnknown(m)
}

var xxx_messageInfo_Review proto.InternalMessageInfo

func (m *Review) GetPressName() string {
	if m != nil {
		return m.PressName
	}
	return ""
}

func (m *Review) GetLink() string {
	if m != nil {
		return m.Link
	}
	return ""
}

func (m *Review) GetScore() string {
	if m != nil {
		return m.Score
	}
	return ""
}

func (m *Review) GetQuote() string {
	if m != nil {
		return m.Quote
	}
	return ""
}

func init() {
	proto.RegisterType((*FindByTitleRequest)(nil), "proto.FindByTitleRequest")
	proto.RegisterType((*GetBySlugRequest)(nil), "proto.GetBySlugRequest")
	proto.RegisterType((*GetByIDRequest)(nil), "proto.GetByIDRequest")
	proto.RegisterType((*Request)(nil), "proto.Request")
	proto.RegisterType((*SearchByTitleResponse)(nil), "proto.SearchByTitleResponse")
	proto.RegisterType((*GameResponse)(nil), "proto.GameResponse")
	proto.RegisterType((*Game)(nil), "proto.Game")
	proto.RegisterType((*Media)(nil), "proto.Media")
	proto.RegisterType((*Tag)(nil), "proto.Tag")
	proto.RegisterType((*Developer)(nil), "proto.Developer")
	proto.RegisterType((*Feature)(nil), "proto.Feature")
	proto.RegisterType((*Genre)(nil), "proto.Genre")
	proto.RegisterType((*Publisher)(nil), "proto.Publisher")
	proto.RegisterType((*SystemRequirements)(nil), "proto.SystemRequirements")
	proto.RegisterType((*RequirementsSet)(nil), "proto.RequirementsSet")
	proto.RegisterType((*Localization)(nil), "proto.Localization")
	proto.RegisterType((*SocialLink)(nil), "proto.SocialLink")
	proto.RegisterType((*Rating)(nil), "proto.Rating")
	proto.RegisterType((*Review)(nil), "proto.Review")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/game.proto", fileDescriptor_07bb4d05826a653a)
}

var fileDescriptor_07bb4d05826a653a = []byte{
	// 1044 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x56, 0x4b, 0x6f, 0xe3, 0x36,
	0x10, 0x5e, 0x27, 0x7e, 0x8e, 0x63, 0x27, 0xcb, 0x3c, 0xaa, 0x0d, 0x16, 0x69, 0x2a, 0xf4, 0xe1,
	0xb6, 0xe8, 0x3a, 0xc8, 0x1e, 0xfa, 0x42, 0x0f, 0x4e, 0x8d, 0x0d, 0x5c, 0x64, 0xb7, 0x2e, 0x9d,
	0x00, 0x45, 0x6f, 0x8a, 0x4c, 0x2b, 0x44, 0xf4, 0x2a, 0x49, 0x65, 0xe1, 0xa2, 0xbf, 0xa1, 0xa7,
	0x1e, 0x7b, 0xeb, 0x1f, 0x2d, 0x86, 0x22, 0x25, 0xd9, 0x49, 0xd0, 0x9c, 0xc4, 0xf9, 0xe6, 0x9b,
	0xd1, 0x70, 0x38, 0xc3, 0x21, 0xbc, 0x48, 0x6f, 0x83, 0x61, 0x20, 0x52, 0x7f, 0x98, 0x8a, 0x44,
	0x25, 0xc3, 0xc0, 0x8b, 0xd8, 0x2b, 0xbd, 0x24, 0x0d, 0xfd, 0x71, 0x7f, 0x05, 0xf2, 0x86, 0xc7,
	0xf3, 0xb3, 0xe5, 0x25, 0x57, 0x21, 0xa3, 0xec, 0xf7, 0x8c, 0x49, 0x45, 0xf6, 0xa0, 0xa1, 0x50,
	0x76, 0x6a, 0xc7, 0xb5, 0x41, 0x87, 0xe6, 0x02, 0x39, 0x80, 0x66, 0xb2, 0x58, 0x48, 0xa6, 0x9c,
	0x8d, 0xe3, 0xda, 0xa0, 0x47, 0x8d, 0x84, 0xec, 0x90, 0x47, 0x5c, 0x39, 0x9b, 0x1a, 0xce, 0x05,
	0xf7, 0x53, 0xd8, 0x39, 0x67, 0xea, 0x6c, 0x39, 0x0b, 0xb3, 0xc0, 0xfa, 0x25, 0x50, 0x97, 0x61,
	0x16, 0x18, 0xb7, 0x7a, 0xed, 0x0e, 0xa0, 0xaf, 0x79, 0x93, 0xb1, 0x65, 0x1d, 0x40, 0x13, 0x03,
	0x9d, 0x8c, 0x0d, 0xcf, 0x48, 0xee, 0x08, 0x5a, 0xff, 0x43, 0x21, 0x47, 0x00, 0x82, 0xdd, 0x71,
	0xc9, 0x93, 0x78, 0x32, 0xd6, 0x61, 0xd6, 0x69, 0x05, 0x71, 0xbf, 0x83, 0xfd, 0x19, 0xf3, 0x84,
	0x7f, 0x53, 0x6c, 0x58, 0xa6, 0x49, 0x2c, 0x19, 0xf9, 0x08, 0x1a, 0xe8, 0x42, 0x3a, 0xb5, 0xe3,
	0xcd, 0x41, 0xf7, 0xb4, 0x9b, 0x67, 0xe9, 0xd5, 0xb9, 0x17, 0x31, 0x9a, 0x6b, 0xdc, 0x21, 0x6c,
	0x69, 0xd1, 0x9a, 0x7c, 0x08, 0x75, 0x54, 0xe8, 0x08, 0xd6, 0x2c, 0xb4, 0xc2, 0xfd, 0xb7, 0x09,
	0x75, 0x14, 0x49, 0x1f, 0x36, 0x8a, 0x48, 0x37, 0x26, 0xe3, 0x32, 0xbd, 0x1b, 0xd5, 0xf4, 0x12,
	0xa8, 0xab, 0x65, 0xca, 0x74, 0x16, 0x3b, 0x54, 0xaf, 0xd7, 0xf6, 0x53, 0x5f, 0xdf, 0x0f, 0x71,
	0xa0, 0x25, 0xb3, 0x28, 0xf2, 0xc4, 0xd2, 0x69, 0x68, 0x33, 0x2b, 0x92, 0x63, 0xe8, 0xce, 0x99,
	0xf4, 0x05, 0x4f, 0x15, 0x4f, 0x62, 0xa7, 0xa9, 0xb5, 0x55, 0xa8, 0x38, 0x8c, 0x56, 0x79, 0x18,
	0xe8, 0x2f, 0xe4, 0x3e, 0x8b, 0x25, 0x73, 0xda, 0xb9, 0x3f, 0x23, 0x92, 0x97, 0xd0, 0x49, 0x43,
	0x4f, 0x2d, 0x12, 0x11, 0x49, 0xa7, 0x73, 0xbc, 0x39, 0xe8, 0xd0, 0x12, 0x20, 0x47, 0x50, 0x57,
	0x5e, 0x20, 0x1d, 0xd0, 0xd9, 0x03, 0x93, 0x8b, 0x4b, 0x2f, 0xa0, 0x1a, 0x27, 0x5f, 0x40, 0x7b,
	0xc1, 0x3c, 0x95, 0x09, 0x26, 0x9d, 0xae, 0xe6, 0xf4, 0x0d, 0xe7, 0x4d, 0x0e, 0xd3, 0x42, 0x4f,
	0x4e, 0x00, 0xe6, 0xec, 0x8e, 0x85, 0x49, 0xca, 0x84, 0x74, 0xb6, 0x34, 0x7b, 0xc7, 0xb0, 0xc7,
	0x56, 0x41, 0x2b, 0x1c, 0xf2, 0x31, 0x34, 0x03, 0x16, 0xa3, 0xef, 0x9e, 0x66, 0x6f, 0xd9, 0xb3,
	0x40, 0x90, 0x1a, 0x1d, 0xfa, 0x4d, 0xb3, 0xeb, 0x90, 0xcb, 0x1b, 0xf4, 0xdb, 0x5f, 0xf1, 0x3b,
	0xb5, 0x0a, 0x5a, 0xe1, 0x90, 0x09, 0x10, 0xb9, 0x94, 0x8a, 0x45, 0x58, 0x76, 0x5c, 0xb0, 0x88,
	0xc5, 0x4a, 0x3a, 0xdb, 0xda, 0xf2, 0x85, 0xb1, 0x9c, 0xdd, 0x23, 0xd0, 0x07, 0x8c, 0xc8, 0xb7,
	0xd0, 0x0b, 0x13, 0xdf, 0x0b, 0xf9, 0x1f, 0x1e, 0x26, 0x5f, 0x3a, 0x3b, 0xda, 0xcb, 0xae, 0xf1,
	0x72, 0x51, 0xd1, 0xd1, 0x55, 0x26, 0x9e, 0x89, 0x12, 0x1e, 0x0f, 0x99, 0x70, 0x9e, 0xe7, 0x67,
	0x62, 0x44, 0xf2, 0x1a, 0xba, 0x32, 0xf1, 0xb9, 0x17, 0x5e, 0xf0, 0xf8, 0x56, 0x3a, 0x44, 0xbb,
	0x7c, 0x6e, 0x03, 0x2b, 0x34, 0xb4, 0xca, 0x22, 0x9f, 0x40, 0x53, 0x78, 0x8a, 0xc7, 0x81, 0xb3,
	0xab, 0xf9, 0x3d, 0xc3, 0xa7, 0x1a, 0xa4, 0x46, 0x49, 0x5c, 0x68, 0x44, 0x6c, 0xce, 0x3d, 0x67,
	0x6f, 0x25, 0xa5, 0x6f, 0x11, 0xa3, 0xb9, 0x8a, 0x7c, 0x06, 0x2d, 0xac, 0x45, 0xf6, 0x5e, 0x3a,
	0xfb, 0xab, 0xbe, 0x34, 0x4a, 0xad, 0x96, 0x1c, 0x42, 0x3b, 0x0d, 0xbd, 0xe5, 0x25, 0x8f, 0x98,
	0x73, 0xa0, 0x2f, 0x89, 0x42, 0x76, 0xbf, 0x82, 0x86, 0x76, 0x5a, 0xd4, 0x7f, 0xad, 0x52, 0xff,
	0x3b, 0xb0, 0x99, 0x89, 0xd0, 0xf4, 0x09, 0x2e, 0xdd, 0xcf, 0x61, 0xf3, 0xd2, 0x0b, 0x2a, 0x2d,
	0x55, 0xd7, 0x2d, 0x45, 0xa0, 0x1e, 0x63, 0x33, 0xe6, 0x4c, 0xbd, 0x76, 0x87, 0xd0, 0x29, 0xea,
	0xe5, 0x49, 0x06, 0x23, 0x68, 0x99, 0x72, 0x7c, 0x0a, 0x1d, 0x31, 0xee, 0x27, 0xb1, 0x6d, 0x58,
	0x5c, 0xbb, 0x5f, 0x42, 0x43, 0x57, 0xdd, 0x53, 0x03, 0x2c, 0x0a, 0xef, 0x49, 0x06, 0xff, 0xd4,
	0x80, 0xdc, 0x2f, 0x38, 0x93, 0x5e, 0xdd, 0x8a, 0x26, 0x7b, 0x85, 0x4c, 0x4e, 0xa0, 0x15, 0xf1,
	0x98, 0x47, 0x5e, 0x9e, 0xc5, 0xee, 0xe9, 0x41, 0x71, 0x46, 0xa5, 0x87, 0x19, 0x53, 0xd4, 0xd2,
	0xc8, 0x37, 0xd0, 0x15, 0xcc, 0x4f, 0xa2, 0x88, 0xc5, 0x73, 0x36, 0xd7, 0xbb, 0x7b, 0xdc, 0xaa,
	0x4a, 0x75, 0x19, 0x6c, 0xaf, 0xe9, 0xf1, 0x00, 0x7f, 0x9c, 0x5e, 0x99, 0xa8, 0x70, 0x89, 0xc8,
	0xf9, 0xf4, 0xca, 0x1e, 0xe9, 0xf9, 0xf4, 0x0a, 0xaf, 0x96, 0x31, 0x97, 0xb7, 0xb3, 0xd4, 0xf3,
	0x99, 0x99, 0x21, 0x25, 0x80, 0x7c, 0x3a, 0x7a, 0xab, 0xef, 0xbe, 0x1e, 0xc5, 0xa5, 0xfb, 0x27,
	0x6c, 0x55, 0xfb, 0x05, 0xb7, 0x7f, 0xe1, 0xc5, 0x41, 0xe6, 0x05, 0xb6, 0x78, 0x0a, 0x19, 0x7d,
	0x4f, 0x62, 0xc5, 0xc4, 0x02, 0x7d, 0xe3, 0x3f, 0xdb, 0xb4, 0x04, 0xf0, 0x22, 0x1e, 0x65, 0x73,
	0x9e, 0xe8, 0xbf, 0xb6, 0x69, 0x2e, 0xa0, 0xcd, 0x2c, 0xbb, 0xd6, 0x97, 0xb2, 0xd4, 0xff, 0x6d,
	0xd3, 0x12, 0x70, 0x8f, 0x00, 0xca, 0xd6, 0xb2, 0x05, 0x5a, 0x2b, 0x0b, 0xf4, 0xef, 0x1a, 0x34,
	0xf3, 0x5e, 0xc2, 0x29, 0x35, 0x0a, 0x58, 0xec, 0x2f, 0xed, 0x94, 0xca, 0x25, 0xc4, 0x73, 0x86,
	0xc9, 0x82, 0xe5, 0x9f, 0xc0, 0xee, 0x98, 0x4b, 0xec, 0x8c, 0x9f, 0xe3, 0x90, 0xc7, 0xec, 0x5d,
	0xa2, 0xb8, 0x49, 0x49, 0x9b, 0x3e, 0xa4, 0x22, 0x03, 0xd8, 0x9e, 0xdd, 0x24, 0xef, 0x47, 0x01,
	0x8e, 0x25, 0x25, 0xb8, 0xaf, 0x4c, 0xc0, 0xeb, 0xb0, 0xbb, 0x80, 0x66, 0xde, 0x95, 0xb8, 0xbd,
	0xa9, 0x60, 0x52, 0xbe, 0xb3, 0xc3, 0xab, 0x43, 0x4b, 0x00, 0xcb, 0x0e, 0x37, 0x66, 0xcb, 0x4e,
	0x6f, 0x72, 0x0f, 0x1a, 0x33, 0x3f, 0x11, 0x76, 0x34, 0xe5, 0x02, 0xa2, 0xbf, 0x64, 0x89, 0x62,
	0xfa, 0x8f, 0x1d, 0x9a, 0x0b, 0xa7, 0x7f, 0x6d, 0x40, 0x17, 0x87, 0xde, 0x8c, 0x89, 0x3b, 0x8c,
	0xf0, 0x07, 0xd8, 0x33, 0xe3, 0x7d, 0x14, 0xcf, 0x69, 0x39, 0xb9, 0xfa, 0x95, 0x82, 0x62, 0x52,
	0x1d, 0xee, 0x56, 0xe7, 0xa7, 0x19, 0xb1, 0xee, 0x33, 0xf2, 0x3d, 0x74, 0x8a, 0x57, 0x04, 0xf9,
	0xa0, 0xb8, 0xd7, 0x57, 0xdf, 0x15, 0x8f, 0x19, 0x7f, 0x0d, 0x2d, 0xf3, 0x6f, 0xb2, 0x5f, 0x35,
	0x2d, 0x9e, 0x1a, 0x8f, 0x19, 0xfe, 0x04, 0xbd, 0x95, 0x67, 0x02, 0xb1, 0xb7, 0xfd, 0xfd, 0xb7,
	0xd2, 0xe1, 0x4b, 0x7b, 0xdf, 0x3e, 0xf4, 0xae, 0x70, 0x9f, 0x9d, 0xed, 0xfc, 0xd6, 0x5f, 0x7d,
	0x85, 0x5d, 0x37, 0xf5, 0xe7, 0xf5, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xcb, 0x57, 0xed, 0xb4,
	0x9e, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GameServiceClient is the client API for GameService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GameServiceClient interface {
	GetByIDAndRevisionID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GameResponse, error)
	// GetBySlug returns latest published game by slug
	GetBySlug(ctx context.Context, in *GetBySlugRequest, opts ...grpc.CallOption) (*GameResponse, error)
	// GetByID returns latest published game by slug
	GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GameResponse, error)
	// FindByTitle returns list of games found by title substring
	SearchByTitle(ctx context.Context, in *FindByTitleRequest, opts ...grpc.CallOption) (*SearchByTitleResponse, error)
}

type gameServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGameServiceClient(cc grpc.ClientConnInterface) GameServiceClient {
	return &gameServiceClient{cc}
}

func (c *gameServiceClient) GetByIDAndRevisionID(ctx context.Context, in *Request, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/proto.GameService/GetByIDAndRevisionID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetBySlug(ctx context.Context, in *GetBySlugRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/proto.GameService/GetBySlug", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) GetByID(ctx context.Context, in *GetByIDRequest, opts ...grpc.CallOption) (*GameResponse, error) {
	out := new(GameResponse)
	err := c.cc.Invoke(ctx, "/proto.GameService/GetByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameServiceClient) SearchByTitle(ctx context.Context, in *FindByTitleRequest, opts ...grpc.CallOption) (*SearchByTitleResponse, error) {
	out := new(SearchByTitleResponse)
	err := c.cc.Invoke(ctx, "/proto.GameService/SearchByTitle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameServiceServer is the server API for GameService service.
type GameServiceServer interface {
	GetByIDAndRevisionID(context.Context, *Request) (*GameResponse, error)
	// GetBySlug returns latest published game by slug
	GetBySlug(context.Context, *GetBySlugRequest) (*GameResponse, error)
	// GetByID returns latest published game by slug
	GetByID(context.Context, *GetByIDRequest) (*GameResponse, error)
	// FindByTitle returns list of games found by title substring
	SearchByTitle(context.Context, *FindByTitleRequest) (*SearchByTitleResponse, error)
}

// UnimplementedGameServiceServer can be embedded to have forward compatible implementations.
type UnimplementedGameServiceServer struct {
}

func (*UnimplementedGameServiceServer) GetByIDAndRevisionID(ctx context.Context, req *Request) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByIDAndRevisionID not implemented")
}
func (*UnimplementedGameServiceServer) GetBySlug(ctx context.Context, req *GetBySlugRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBySlug not implemented")
}
func (*UnimplementedGameServiceServer) GetByID(ctx context.Context, req *GetByIDRequest) (*GameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByID not implemented")
}
func (*UnimplementedGameServiceServer) SearchByTitle(ctx context.Context, req *FindByTitleRequest) (*SearchByTitleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByTitle not implemented")
}

func RegisterGameServiceServer(s *grpc.Server, srv GameServiceServer) {
	s.RegisterService(&_GameService_serviceDesc, srv)
}

func _GameService_GetByIDAndRevisionID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetByIDAndRevisionID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameService/GetByIDAndRevisionID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetByIDAndRevisionID(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetBySlug_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBySlugRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetBySlug(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameService/GetBySlug",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetBySlug(ctx, req.(*GetBySlugRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_GetByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).GetByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameService/GetByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).GetByID(ctx, req.(*GetByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameService_SearchByTitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindByTitleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameServiceServer).SearchByTitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.GameService/SearchByTitle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameServiceServer).SearchByTitle(ctx, req.(*FindByTitleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _GameService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GameService",
	HandlerType: (*GameServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetByIDAndRevisionID",
			Handler:    _GameService_GetByIDAndRevisionID_Handler,
		},
		{
			MethodName: "GetBySlug",
			Handler:    _GameService_GetBySlug_Handler,
		},
		{
			MethodName: "GetByID",
			Handler:    _GameService_GetByID_Handler,
		},
		{
			MethodName: "SearchByTitle",
			Handler:    _GameService_SearchByTitle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/game.proto",
}
