// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pkg/grpc/proto/storefront.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetActiveStorefrontRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetActiveStorefrontRequest) Reset()         { *m = GetActiveStorefrontRequest{} }
func (m *GetActiveStorefrontRequest) String() string { return proto.CompactTextString(m) }
func (*GetActiveStorefrontRequest) ProtoMessage()    {}
func (*GetActiveStorefrontRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cf4b405918b974, []int{0}
}

func (m *GetActiveStorefrontRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetActiveStorefrontRequest.Unmarshal(m, b)
}
func (m *GetActiveStorefrontRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetActiveStorefrontRequest.Marshal(b, m, deterministic)
}
func (m *GetActiveStorefrontRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetActiveStorefrontRequest.Merge(m, src)
}
func (m *GetActiveStorefrontRequest) XXX_Size() int {
	return xxx_messageInfo_GetActiveStorefrontRequest.Size(m)
}
func (m *GetActiveStorefrontRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetActiveStorefrontRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetActiveStorefrontRequest proto.InternalMessageInfo

type StorefrontResponse struct {
	Storefront           *Storefront `protobuf:"bytes,1,opt,name=storefront,proto3" json:"storefront,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *StorefrontResponse) Reset()         { *m = StorefrontResponse{} }
func (m *StorefrontResponse) String() string { return proto.CompactTextString(m) }
func (*StorefrontResponse) ProtoMessage()    {}
func (*StorefrontResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cf4b405918b974, []int{1}
}

func (m *StorefrontResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StorefrontResponse.Unmarshal(m, b)
}
func (m *StorefrontResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StorefrontResponse.Marshal(b, m, deterministic)
}
func (m *StorefrontResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StorefrontResponse.Merge(m, src)
}
func (m *StorefrontResponse) XXX_Size() int {
	return xxx_messageInfo_StorefrontResponse.Size(m)
}
func (m *StorefrontResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StorefrontResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StorefrontResponse proto.InternalMessageInfo

func (m *StorefrontResponse) GetStorefront() *Storefront {
	if m != nil {
		return m.Storefront
	}
	return nil
}

type Storefront struct {
	Blocks               []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Storefront) Reset()         { *m = Storefront{} }
func (m *Storefront) String() string { return proto.CompactTextString(m) }
func (*Storefront) ProtoMessage()    {}
func (*Storefront) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cf4b405918b974, []int{2}
}

func (m *Storefront) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Storefront.Unmarshal(m, b)
}
func (m *Storefront) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Storefront.Marshal(b, m, deterministic)
}
func (m *Storefront) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Storefront.Merge(m, src)
}
func (m *Storefront) XXX_Size() int {
	return xxx_messageInfo_Storefront.Size(m)
}
func (m *Storefront) XXX_DiscardUnknown() {
	xxx_messageInfo_Storefront.DiscardUnknown(m)
}

var xxx_messageInfo_Storefront proto.InternalMessageInfo

func (m *Storefront) GetBlocks() []*Block {
	if m != nil {
		return m.Blocks
	}
	return nil
}

type Block struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Filter               string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	GameIds              []string `protobuf:"bytes,4,rep,name=gameIds,proto3" json:"gameIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Block) Reset()         { *m = Block{} }
func (m *Block) String() string { return proto.CompactTextString(m) }
func (*Block) ProtoMessage()    {}
func (*Block) Descriptor() ([]byte, []int) {
	return fileDescriptor_f4cf4b405918b974, []int{3}
}

func (m *Block) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Block.Unmarshal(m, b)
}
func (m *Block) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Block.Marshal(b, m, deterministic)
}
func (m *Block) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Block.Merge(m, src)
}
func (m *Block) XXX_Size() int {
	return xxx_messageInfo_Block.Size(m)
}
func (m *Block) XXX_DiscardUnknown() {
	xxx_messageInfo_Block.DiscardUnknown(m)
}

var xxx_messageInfo_Block proto.InternalMessageInfo

func (m *Block) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Block) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Block) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *Block) GetGameIds() []string {
	if m != nil {
		return m.GameIds
	}
	return nil
}

func init() {
	proto.RegisterType((*GetActiveStorefrontRequest)(nil), "proto.GetActiveStorefrontRequest")
	proto.RegisterType((*StorefrontResponse)(nil), "proto.StorefrontResponse")
	proto.RegisterType((*Storefront)(nil), "proto.Storefront")
	proto.RegisterType((*Block)(nil), "proto.Block")
}

func init() {
	proto.RegisterFile("pkg/grpc/proto/storefront.proto", fileDescriptor_f4cf4b405918b974)
}

var fileDescriptor_f4cf4b405918b974 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0xad, 0x69, 0x22, 0x99, 0x8a, 0xd8, 0x41, 0x64, 0x2d, 0x82, 0x71, 0xf1, 0x90, 0x53,
	0x83, 0xf1, 0x17, 0xd8, 0x4b, 0x11, 0x6f, 0xe9, 0xcd, 0x93, 0x76, 0x9d, 0x86, 0xd0, 0xd8, 0x5d,
	0x77, 0xc7, 0x82, 0xff, 0x5e, 0xdc, 0xae, 0x4d, 0x44, 0x3c, 0x4d, 0xde, 0x37, 0x2f, 0xb3, 0xb3,
	0x6f, 0xe1, 0xca, 0xac, 0xeb, 0xa2, 0xb6, 0x46, 0x15, 0xc6, 0x6a, 0xd6, 0x85, 0x63, 0x6d, 0x69,
	0x65, 0xf5, 0x86, 0xa7, 0x1e, 0x60, 0xec, 0x8b, 0xbc, 0x84, 0xc9, 0x9c, 0xf8, 0x5e, 0x71, 0xb3,
	0xa5, 0xc5, 0xde, 0x53, 0xd1, 0xfb, 0x07, 0x39, 0x96, 0x73, 0xc0, 0x3e, 0x74, 0x46, 0x6f, 0x1c,
	0xe1, 0x2d, 0x40, 0x37, 0x4e, 0x0c, 0xb2, 0x41, 0x3e, 0x2a, 0xc7, 0xbb, 0xb1, 0xd3, 0x9e, 0xbd,
	0x67, 0x92, 0x25, 0x40, 0xd7, 0xc1, 0x1b, 0x48, 0x96, 0xad, 0x56, 0x6b, 0x27, 0x06, 0x59, 0x94,
	0x8f, 0xca, 0xe3, 0xf0, 0xf3, 0xec, 0x1b, 0x56, 0xa1, 0x27, 0x15, 0xc4, 0x1e, 0x20, 0xc2, 0x90,
	0x3f, 0x0d, 0xf9, 0x93, 0xd2, 0xca, 0x7f, 0xe3, 0x19, 0xc4, 0xdc, 0x70, 0x4b, 0xe2, 0xd0, 0xc3,
	0x9d, 0xc0, 0x73, 0x48, 0x56, 0x4d, 0xcb, 0x64, 0x45, 0xe4, 0x71, 0x50, 0x28, 0xe0, 0xa8, 0x7e,
	0x79, 0xa3, 0x87, 0x57, 0x27, 0x86, 0x59, 0x94, 0xa7, 0xd5, 0x8f, 0x2c, 0x9f, 0x61, 0xdc, 0x2d,
	0xb6, 0x20, 0xbb, 0x6d, 0x14, 0xe1, 0x23, 0xa4, 0xfb, 0x50, 0xf0, 0x3a, 0x2c, 0xf7, 0x7f, 0x4c,
	0x93, 0x8b, 0xbf, 0x97, 0x0f, 0x59, 0xc9, 0x83, 0xd9, 0xe9, 0xd3, 0xc9, 0xef, 0xb7, 0x58, 0x26,
	0xbe, 0xdc, 0x7d, 0x05, 0x00, 0x00, 0xff, 0xff, 0xdd, 0x74, 0x7c, 0x93, 0xa4, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorefrontServiceClient is the client API for StorefrontService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorefrontServiceClient interface {
	GetActive(ctx context.Context, in *GetActiveStorefrontRequest, opts ...grpc.CallOption) (*StorefrontResponse, error)
}

type storefrontServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorefrontServiceClient(cc grpc.ClientConnInterface) StorefrontServiceClient {
	return &storefrontServiceClient{cc}
}

func (c *storefrontServiceClient) GetActive(ctx context.Context, in *GetActiveStorefrontRequest, opts ...grpc.CallOption) (*StorefrontResponse, error) {
	out := new(StorefrontResponse)
	err := c.cc.Invoke(ctx, "/proto.StorefrontService/GetActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorefrontServiceServer is the server API for StorefrontService service.
type StorefrontServiceServer interface {
	GetActive(context.Context, *GetActiveStorefrontRequest) (*StorefrontResponse, error)
}

// UnimplementedStorefrontServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorefrontServiceServer struct {
}

func (*UnimplementedStorefrontServiceServer) GetActive(ctx context.Context, req *GetActiveStorefrontRequest) (*StorefrontResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActive not implemented")
}

func RegisterStorefrontServiceServer(s *grpc.Server, srv StorefrontServiceServer) {
	s.RegisterService(&_StorefrontService_serviceDesc, srv)
}

func _StorefrontService_GetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveStorefrontRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorefrontServiceServer).GetActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StorefrontService/GetActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorefrontServiceServer).GetActive(ctx, req.(*GetActiveStorefrontRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorefrontService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StorefrontService",
	HandlerType: (*StorefrontServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActive",
			Handler:    _StorefrontService_GetActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/storefront.proto",
}
