// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.21.0
// 	protoc        v3.11.4
// source: pkg/grpc/proto/storefront.proto

package proto

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetActiveStorefrontRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetActiveStorefrontRequest) Reset() {
	*x = GetActiveStorefrontRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetActiveStorefrontRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActiveStorefrontRequest) ProtoMessage() {}

func (x *GetActiveStorefrontRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActiveStorefrontRequest.ProtoReflect.Descriptor instead.
func (*GetActiveStorefrontRequest) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_storefront_proto_rawDescGZIP(), []int{0}
}

type StorefrontResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Storefront *Storefront `protobuf:"bytes,1,opt,name=storefront,proto3" json:"storefront,omitempty"`
}

func (x *StorefrontResponse) Reset() {
	*x = StorefrontResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StorefrontResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorefrontResponse) ProtoMessage() {}

func (x *StorefrontResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorefrontResponse.ProtoReflect.Descriptor instead.
func (*StorefrontResponse) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_storefront_proto_rawDescGZIP(), []int{1}
}

func (x *StorefrontResponse) GetStorefront() *Storefront {
	if x != nil {
		return x.Storefront
	}
	return nil
}

type Storefront struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blocks []*Block `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"`
}

func (x *Storefront) Reset() {
	*x = Storefront{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Storefront) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Storefront) ProtoMessage() {}

func (x *Storefront) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Storefront.ProtoReflect.Descriptor instead.
func (*Storefront) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_storefront_proto_rawDescGZIP(), []int{2}
}

func (x *Storefront) GetBlocks() []*Block {
	if x != nil {
		return x.Blocks
	}
	return nil
}

type Block struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type    string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Title   string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Filter  string   `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	GameIds []string `protobuf:"bytes,4,rep,name=gameIds,proto3" json:"gameIds,omitempty"`
}

func (x *Block) Reset() {
	*x = Block{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Block) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Block) ProtoMessage() {}

func (x *Block) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_grpc_proto_storefront_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Block.ProtoReflect.Descriptor instead.
func (*Block) Descriptor() ([]byte, []int) {
	return file_pkg_grpc_proto_storefront_proto_rawDescGZIP(), []int{3}
}

func (x *Block) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Block) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Block) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *Block) GetGameIds() []string {
	if x != nil {
		return x.GameIds
	}
	return nil
}

var File_pkg_grpc_proto_storefront_proto protoreflect.FileDescriptor

var file_pkg_grpc_proto_storefront_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x1c, 0x0a, 0x1a, 0x47, 0x65, 0x74, 0x41,
	0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x47, 0x0a, 0x12, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x66,
	0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x0a,
	0x73, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x11, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x52, 0x0a, 0x73, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x22,
	0x32, 0x0a, 0x0a, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x12, 0x24, 0x0a,
	0x06, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x52, 0x06, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x22, 0x63, 0x0a, 0x05, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x12, 0x12, 0x0a, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x67, 0x61, 0x6d, 0x65, 0x49, 0x64, 0x73, 0x32, 0x60, 0x0a, 0x11, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a,
	0x09, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x12, 0x21, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x74, 0x69, 0x76, 0x65, 0x53, 0x74, 0x6f, 0x72,
	0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x66, 0x72, 0x6f, 0x6e, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b,
	0x67, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_grpc_proto_storefront_proto_rawDescOnce sync.Once
	file_pkg_grpc_proto_storefront_proto_rawDescData = file_pkg_grpc_proto_storefront_proto_rawDesc
)

func file_pkg_grpc_proto_storefront_proto_rawDescGZIP() []byte {
	file_pkg_grpc_proto_storefront_proto_rawDescOnce.Do(func() {
		file_pkg_grpc_proto_storefront_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_grpc_proto_storefront_proto_rawDescData)
	})
	return file_pkg_grpc_proto_storefront_proto_rawDescData
}

var file_pkg_grpc_proto_storefront_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_grpc_proto_storefront_proto_goTypes = []interface{}{
	(*GetActiveStorefrontRequest)(nil), // 0: proto.GetActiveStorefrontRequest
	(*StorefrontResponse)(nil),         // 1: proto.StorefrontResponse
	(*Storefront)(nil),                 // 2: proto.Storefront
	(*Block)(nil),                      // 3: proto.Block
}
var file_pkg_grpc_proto_storefront_proto_depIdxs = []int32{
	2, // 0: proto.StorefrontResponse.storefront:type_name -> proto.Storefront
	3, // 1: proto.Storefront.blocks:type_name -> proto.Block
	0, // 2: proto.StorefrontService.GetActive:input_type -> proto.GetActiveStorefrontRequest
	1, // 3: proto.StorefrontService.GetActive:output_type -> proto.StorefrontResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_grpc_proto_storefront_proto_init() }
func file_pkg_grpc_proto_storefront_proto_init() {
	if File_pkg_grpc_proto_storefront_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_grpc_proto_storefront_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetActiveStorefrontRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_storefront_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StorefrontResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_storefront_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Storefront); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_grpc_proto_storefront_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Block); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_grpc_proto_storefront_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_grpc_proto_storefront_proto_goTypes,
		DependencyIndexes: file_pkg_grpc_proto_storefront_proto_depIdxs,
		MessageInfos:      file_pkg_grpc_proto_storefront_proto_msgTypes,
	}.Build()
	File_pkg_grpc_proto_storefront_proto = out.File
	file_pkg_grpc_proto_storefront_proto_rawDesc = nil
	file_pkg_grpc_proto_storefront_proto_goTypes = nil
	file_pkg_grpc_proto_storefront_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// StorefrontServiceClient is the client API for StorefrontService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorefrontServiceClient interface {
	GetActive(ctx context.Context, in *GetActiveStorefrontRequest, opts ...grpc.CallOption) (*StorefrontResponse, error)
}

type storefrontServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStorefrontServiceClient(cc grpc.ClientConnInterface) StorefrontServiceClient {
	return &storefrontServiceClient{cc}
}

func (c *storefrontServiceClient) GetActive(ctx context.Context, in *GetActiveStorefrontRequest, opts ...grpc.CallOption) (*StorefrontResponse, error) {
	out := new(StorefrontResponse)
	err := c.cc.Invoke(ctx, "/proto.StorefrontService/GetActive", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorefrontServiceServer is the server API for StorefrontService service.
type StorefrontServiceServer interface {
	GetActive(context.Context, *GetActiveStorefrontRequest) (*StorefrontResponse, error)
}

// UnimplementedStorefrontServiceServer can be embedded to have forward compatible implementations.
type UnimplementedStorefrontServiceServer struct {
}

func (*UnimplementedStorefrontServiceServer) GetActive(context.Context, *GetActiveStorefrontRequest) (*StorefrontResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetActive not implemented")
}

func RegisterStorefrontServiceServer(s *grpc.Server, srv StorefrontServiceServer) {
	s.RegisterService(&_StorefrontService_serviceDesc, srv)
}

func _StorefrontService_GetActive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetActiveStorefrontRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorefrontServiceServer).GetActive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.StorefrontService/GetActive",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorefrontServiceServer).GetActive(ctx, req.(*GetActiveStorefrontRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorefrontService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.StorefrontService",
	HandlerType: (*StorefrontServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetActive",
			Handler:    _StorefrontService_GetActive_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/grpc/proto/storefront.proto",
}
